/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "uav_type_man"."ammo_launch_way" CASCADE;

CREATE TABLE "uav_type_man"."ammo_launch_way" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "ammo_launch_code" TEXT NOT NULL,
  "ammo_launch_name" TEXT NOT NULL,
  "status" BOOLEAN NOT NULL);

