// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "AmmunitionEntity-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // AmmunitionEntity
  //

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  persist_statement_name[] = "persist_AmmunitionEntity";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  find_statement_name[] = "find_AmmunitionEntity";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  update_statement_name[] = "update_AmmunitionEntity";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  erase_statement_name[] = "erase_AmmunitionEntity";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  query_statement_name[] = "query_AmmunitionEntity";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  erase_query_statement_name[] = "erase_query_AmmunitionEntity";

  const unsigned int access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::timestamp_oid,
    pgsql::text_oid,
    pgsql::float4_oid
  };

  const unsigned int access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::timestamp_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::id_type
  access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::id_type
  access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // ammoType_
    //
    if (t[1UL])
    {
      i.ammoType_value.capacity (i.ammoType_size);
      grew = true;
    }

    // ammoName_
    //
    if (t[2UL])
    {
      i.ammoName_value.capacity (i.ammoName_size);
      grew = true;
    }

    // ammoId_
    //
    if (t[3UL])
    {
      i.ammoId_value.capacity (i.ammoId_size);
      grew = true;
    }

    // ammoToUavModel_
    //
    if (t[4UL])
    {
      i.ammoToUavModel_value.capacity (i.ammoToUavModel_size);
      grew = true;
    }

    // ammoLength_
    //
    t[5UL] = 0;

    // ammoWidth_
    //
    t[6UL] = 0;

    // ammoWeight_
    //
    t[7UL] = 0;

    // guidanceType_
    //
    if (t[8UL])
    {
      i.guidanceType_value.capacity (i.guidanceType_size);
      grew = true;
    }

    // launchHeightMin_
    //
    t[9UL] = 0;

    // launchHeightMax_
    //
    t[10UL] = 0;

    // launchDistanceMin_
    //
    t[11UL] = 0;

    // launchDistanceMax_
    //
    t[12UL] = 0;

    // launchAngle_
    //
    t[13UL] = 0;

    // launchWay_
    //
    if (t[14UL])
    {
      i.launchWay_value.capacity (i.launchWay_size);
      grew = true;
    }

    // approveAttackTargetType_
    //
    if (t[15UL])
    {
      i.approveAttackTargetType_value.capacity (i.approveAttackTargetType_size);
      grew = true;
    }

    // killingDose_
    //
    t[16UL] = 0;

    // killingMethod_
    //
    if (t[17UL])
    {
      i.killingMethod_value.capacity (i.killingMethod_size);
      grew = true;
    }

    // killingDepth_
    //
    t[18UL] = 0;

    // killingRangeMin_
    //
    t[19UL] = 0;

    // killingRangeMax_
    //
    t[20UL] = 0;

    // recordCreationTime_
    //
    t[21UL] = 0;

    // ammoImgUrl_
    //
    if (t[22UL])
    {
      i.ammoImgUrl_value.capacity (i.ammoImgUrl_size);
      grew = true;
    }

    // ammoImageName_
    //
    t[23UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // ammoType_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.ammoType_value.data ();
    b[n].capacity = i.ammoType_value.capacity ();
    b[n].size = &i.ammoType_size;
    b[n].is_null = &i.ammoType_null;
    n++;

    // ammoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.ammoName_value.data ();
    b[n].capacity = i.ammoName_value.capacity ();
    b[n].size = &i.ammoName_size;
    b[n].is_null = &i.ammoName_null;
    n++;

    // ammoId_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.ammoId_value.data ();
    b[n].capacity = i.ammoId_value.capacity ();
    b[n].size = &i.ammoId_size;
    b[n].is_null = &i.ammoId_null;
    n++;

    // ammoToUavModel_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.ammoToUavModel_value.data ();
    b[n].capacity = i.ammoToUavModel_value.capacity ();
    b[n].size = &i.ammoToUavModel_size;
    b[n].is_null = &i.ammoToUavModel_null;
    n++;

    // ammoLength_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.ammoLength_value;
    b[n].is_null = &i.ammoLength_null;
    n++;

    // ammoWidth_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.ammoWidth_value;
    b[n].is_null = &i.ammoWidth_null;
    n++;

    // ammoWeight_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.ammoWeight_value;
    b[n].is_null = &i.ammoWeight_null;
    n++;

    // guidanceType_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.guidanceType_value.data ();
    b[n].capacity = i.guidanceType_value.capacity ();
    b[n].size = &i.guidanceType_size;
    b[n].is_null = &i.guidanceType_null;
    n++;

    // launchHeightMin_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.launchHeightMin_value;
    b[n].is_null = &i.launchHeightMin_null;
    n++;

    // launchHeightMax_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.launchHeightMax_value;
    b[n].is_null = &i.launchHeightMax_null;
    n++;

    // launchDistanceMin_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.launchDistanceMin_value;
    b[n].is_null = &i.launchDistanceMin_null;
    n++;

    // launchDistanceMax_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.launchDistanceMax_value;
    b[n].is_null = &i.launchDistanceMax_null;
    n++;

    // launchAngle_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.launchAngle_value;
    b[n].is_null = &i.launchAngle_null;
    n++;

    // launchWay_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.launchWay_value.data ();
    b[n].capacity = i.launchWay_value.capacity ();
    b[n].size = &i.launchWay_size;
    b[n].is_null = &i.launchWay_null;
    n++;

    // approveAttackTargetType_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.approveAttackTargetType_value.data ();
    b[n].capacity = i.approveAttackTargetType_value.capacity ();
    b[n].size = &i.approveAttackTargetType_size;
    b[n].is_null = &i.approveAttackTargetType_null;
    n++;

    // killingDose_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.killingDose_value;
    b[n].is_null = &i.killingDose_null;
    n++;

    // killingMethod_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.killingMethod_value.data ();
    b[n].capacity = i.killingMethod_value.capacity ();
    b[n].size = &i.killingMethod_size;
    b[n].is_null = &i.killingMethod_null;
    n++;

    // killingDepth_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.killingDepth_value;
    b[n].is_null = &i.killingDepth_null;
    n++;

    // killingRangeMin_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.killingRangeMin_value;
    b[n].is_null = &i.killingRangeMin_null;
    n++;

    // killingRangeMax_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.killingRangeMax_value;
    b[n].is_null = &i.killingRangeMax_null;
    n++;

    // recordCreationTime_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.recordCreationTime_value;
    b[n].is_null = &i.recordCreationTime_null;
    n++;

    // ammoImgUrl_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.ammoImgUrl_value.data ();
    b[n].capacity = i.ammoImgUrl_value.capacity ();
    b[n].size = &i.ammoImgUrl_size;
    b[n].is_null = &i.ammoImgUrl_null;
    n++;

    // ammoImageName_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.ammoImageName_value;
    b[n].is_null = &i.ammoImageName_null;
    n++;
  }

  void access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // ammoType_
    //
    {
      ::std::string const& v =
        o.ammoType_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.ammoType_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.ammoType_value,
        size,
        is_null,
        v);
      i.ammoType_null = is_null;
      i.ammoType_size = size;
      grew = grew || (cap != i.ammoType_value.capacity ());
    }

    // ammoName_
    //
    {
      ::std::string const& v =
        o.ammoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.ammoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.ammoName_value,
        size,
        is_null,
        v);
      i.ammoName_null = is_null;
      i.ammoName_size = size;
      grew = grew || (cap != i.ammoName_value.capacity ());
    }

    // ammoId_
    //
    {
      ::std::string const& v =
        o.ammoId_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.ammoId_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.ammoId_value,
        size,
        is_null,
        v);
      i.ammoId_null = is_null;
      i.ammoId_size = size;
      grew = grew || (cap != i.ammoId_value.capacity ());
    }

    // ammoToUavModel_
    //
    {
      ::std::string const& v =
        o.ammoToUavModel_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.ammoToUavModel_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.ammoToUavModel_value,
        size,
        is_null,
        v);
      i.ammoToUavModel_null = is_null;
      i.ammoToUavModel_size = size;
      grew = grew || (cap != i.ammoToUavModel_value.capacity ());
    }

    // ammoLength_
    //
    {
      float const& v =
        o.ammoLength_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.ammoLength_value, is_null, v);
      i.ammoLength_null = is_null;
    }

    // ammoWidth_
    //
    {
      float const& v =
        o.ammoWidth_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.ammoWidth_value, is_null, v);
      i.ammoWidth_null = is_null;
    }

    // ammoWeight_
    //
    {
      float const& v =
        o.ammoWeight_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.ammoWeight_value, is_null, v);
      i.ammoWeight_null = is_null;
    }

    // guidanceType_
    //
    {
      ::std::string const& v =
        o.guidanceType_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.guidanceType_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.guidanceType_value,
        size,
        is_null,
        v);
      i.guidanceType_null = is_null;
      i.guidanceType_size = size;
      grew = grew || (cap != i.guidanceType_value.capacity ());
    }

    // launchHeightMin_
    //
    {
      float const& v =
        o.launchHeightMin_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.launchHeightMin_value, is_null, v);
      i.launchHeightMin_null = is_null;
    }

    // launchHeightMax_
    //
    {
      float const& v =
        o.launchHeightMax_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.launchHeightMax_value, is_null, v);
      i.launchHeightMax_null = is_null;
    }

    // launchDistanceMin_
    //
    {
      float const& v =
        o.launchDistanceMin_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.launchDistanceMin_value, is_null, v);
      i.launchDistanceMin_null = is_null;
    }

    // launchDistanceMax_
    //
    {
      float const& v =
        o.launchDistanceMax_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.launchDistanceMax_value, is_null, v);
      i.launchDistanceMax_null = is_null;
    }

    // launchAngle_
    //
    {
      float const& v =
        o.launchAngle_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.launchAngle_value, is_null, v);
      i.launchAngle_null = is_null;
    }

    // launchWay_
    //
    {
      ::std::string const& v =
        o.launchWay_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.launchWay_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.launchWay_value,
        size,
        is_null,
        v);
      i.launchWay_null = is_null;
      i.launchWay_size = size;
      grew = grew || (cap != i.launchWay_value.capacity ());
    }

    // approveAttackTargetType_
    //
    {
      ::std::string const& v =
        o.approveAttackTargetType_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.approveAttackTargetType_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.approveAttackTargetType_value,
        size,
        is_null,
        v);
      i.approveAttackTargetType_null = is_null;
      i.approveAttackTargetType_size = size;
      grew = grew || (cap != i.approveAttackTargetType_value.capacity ());
    }

    // killingDose_
    //
    {
      float const& v =
        o.killingDose_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.killingDose_value, is_null, v);
      i.killingDose_null = is_null;
    }

    // killingMethod_
    //
    {
      ::std::string const& v =
        o.killingMethod_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.killingMethod_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.killingMethod_value,
        size,
        is_null,
        v);
      i.killingMethod_null = is_null;
      i.killingMethod_size = size;
      grew = grew || (cap != i.killingMethod_value.capacity ());
    }

    // killingDepth_
    //
    {
      float const& v =
        o.killingDepth_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.killingDepth_value, is_null, v);
      i.killingDepth_null = is_null;
    }

    // killingRangeMin_
    //
    {
      float const& v =
        o.killingRangeMin_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.killingRangeMin_value, is_null, v);
      i.killingRangeMin_null = is_null;
    }

    // killingRangeMax_
    //
    {
      float const& v =
        o.killingRangeMax_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.killingRangeMax_value, is_null, v);
      i.killingRangeMax_null = is_null;
    }

    // recordCreationTime_
    //
    {
      ::QDateTime const& v =
        o.recordCreationTime_;

      bool is_null (false);
      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_image (
        i.recordCreationTime_value, is_null, v);
      i.recordCreationTime_null = is_null;
    }

    // ammoImgUrl_
    //
    {
      ::std::string const& v =
        o.ammoImgUrl_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.ammoImgUrl_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.ammoImgUrl_value,
        size,
        is_null,
        v);
      i.ammoImgUrl_null = is_null;
      i.ammoImgUrl_size = size;
      grew = grew || (cap != i.ammoImgUrl_value.capacity ());
    }

    // ammoImageName_
    //
    {
      float const& v =
        o.ammoImageName_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.ammoImageName_value, is_null, v);
      i.ammoImageName_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      long int& v =
        o.id_;

      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // ammoType_
    //
    {
      ::std::string& v =
        o.ammoType_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.ammoType_value,
        i.ammoType_size,
        i.ammoType_null);
    }

    // ammoName_
    //
    {
      ::std::string& v =
        o.ammoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.ammoName_value,
        i.ammoName_size,
        i.ammoName_null);
    }

    // ammoId_
    //
    {
      ::std::string& v =
        o.ammoId_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.ammoId_value,
        i.ammoId_size,
        i.ammoId_null);
    }

    // ammoToUavModel_
    //
    {
      ::std::string& v =
        o.ammoToUavModel_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.ammoToUavModel_value,
        i.ammoToUavModel_size,
        i.ammoToUavModel_null);
    }

    // ammoLength_
    //
    {
      float& v =
        o.ammoLength_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.ammoLength_value,
        i.ammoLength_null);
    }

    // ammoWidth_
    //
    {
      float& v =
        o.ammoWidth_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.ammoWidth_value,
        i.ammoWidth_null);
    }

    // ammoWeight_
    //
    {
      float& v =
        o.ammoWeight_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.ammoWeight_value,
        i.ammoWeight_null);
    }

    // guidanceType_
    //
    {
      ::std::string& v =
        o.guidanceType_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.guidanceType_value,
        i.guidanceType_size,
        i.guidanceType_null);
    }

    // launchHeightMin_
    //
    {
      float& v =
        o.launchHeightMin_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.launchHeightMin_value,
        i.launchHeightMin_null);
    }

    // launchHeightMax_
    //
    {
      float& v =
        o.launchHeightMax_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.launchHeightMax_value,
        i.launchHeightMax_null);
    }

    // launchDistanceMin_
    //
    {
      float& v =
        o.launchDistanceMin_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.launchDistanceMin_value,
        i.launchDistanceMin_null);
    }

    // launchDistanceMax_
    //
    {
      float& v =
        o.launchDistanceMax_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.launchDistanceMax_value,
        i.launchDistanceMax_null);
    }

    // launchAngle_
    //
    {
      float& v =
        o.launchAngle_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.launchAngle_value,
        i.launchAngle_null);
    }

    // launchWay_
    //
    {
      ::std::string& v =
        o.launchWay_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.launchWay_value,
        i.launchWay_size,
        i.launchWay_null);
    }

    // approveAttackTargetType_
    //
    {
      ::std::string& v =
        o.approveAttackTargetType_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.approveAttackTargetType_value,
        i.approveAttackTargetType_size,
        i.approveAttackTargetType_null);
    }

    // killingDose_
    //
    {
      float& v =
        o.killingDose_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.killingDose_value,
        i.killingDose_null);
    }

    // killingMethod_
    //
    {
      ::std::string& v =
        o.killingMethod_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.killingMethod_value,
        i.killingMethod_size,
        i.killingMethod_null);
    }

    // killingDepth_
    //
    {
      float& v =
        o.killingDepth_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.killingDepth_value,
        i.killingDepth_null);
    }

    // killingRangeMin_
    //
    {
      float& v =
        o.killingRangeMin_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.killingRangeMin_value,
        i.killingRangeMin_null);
    }

    // killingRangeMax_
    //
    {
      float& v =
        o.killingRangeMax_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.killingRangeMax_value,
        i.killingRangeMax_null);
    }

    // recordCreationTime_
    //
    {
      ::QDateTime& v =
        o.recordCreationTime_;

      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_value (
        v,
        i.recordCreationTime_value,
        i.recordCreationTime_null);
    }

    // ammoImgUrl_
    //
    {
      ::std::string& v =
        o.ammoImgUrl_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.ammoImgUrl_value,
        i.ammoImgUrl_size,
        i.ammoImgUrl_null);
    }

    // ammoImageName_
    //
    {
      float& v =
        o.ammoImageName_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.ammoImageName_value,
        i.ammoImageName_null);
    }
  }

  void access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::persist_statement[] =
  "INSERT INTO \"uav_type_man\".\"ammo_parameters\" "
  "(\"id\", "
  "\"ammo_type\", "
  "\"ammo_name\", "
  "\"ammo_id\", "
  "\"ammo_to_uavmodel\", "
  "\"length\", "
  "\"width\", "
  "\"weight\", "
  "\"guidance_type\", "
  "\"launch_height_min\", "
  "\"launch_height_max\", "
  "\"launch_distance_min\", "
  "\"launch_distance_max\", "
  "\"launch_angle\", "
  "\"launch_method\", "
  "\"approve_attack_target_type\", "
  "\"killing_dose\", "
  "\"killing_method\", "
  "\"killing_depth\", "
  "\"killing_range_min\", "
  "\"killing_range_max\", "
  "\"recordcreation_time\", "
  "\"image_url\", "
  "\"image_name\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::find_statement[] =
  "SELECT "
  "\"uav_type_man\".\"ammo_parameters\".\"id\", "
  "\"uav_type_man\".\"ammo_parameters\".\"ammo_type\", "
  "\"uav_type_man\".\"ammo_parameters\".\"ammo_name\", "
  "\"uav_type_man\".\"ammo_parameters\".\"ammo_id\", "
  "\"uav_type_man\".\"ammo_parameters\".\"ammo_to_uavmodel\", "
  "\"uav_type_man\".\"ammo_parameters\".\"length\", "
  "\"uav_type_man\".\"ammo_parameters\".\"width\", "
  "\"uav_type_man\".\"ammo_parameters\".\"weight\", "
  "\"uav_type_man\".\"ammo_parameters\".\"guidance_type\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_height_min\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_height_max\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_distance_min\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_distance_max\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_angle\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_method\", "
  "\"uav_type_man\".\"ammo_parameters\".\"approve_attack_target_type\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_dose\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_method\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_depth\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_range_min\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_range_max\", "
  "\"uav_type_man\".\"ammo_parameters\".\"recordcreation_time\", "
  "\"uav_type_man\".\"ammo_parameters\".\"image_url\", "
  "\"uav_type_man\".\"ammo_parameters\".\"image_name\" "
  "FROM \"uav_type_man\".\"ammo_parameters\" "
  "WHERE \"uav_type_man\".\"ammo_parameters\".\"id\"=$1";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::update_statement[] =
  "UPDATE \"uav_type_man\".\"ammo_parameters\" "
  "SET "
  "\"ammo_type\"=$1, "
  "\"ammo_name\"=$2, "
  "\"ammo_id\"=$3, "
  "\"ammo_to_uavmodel\"=$4, "
  "\"length\"=$5, "
  "\"width\"=$6, "
  "\"weight\"=$7, "
  "\"guidance_type\"=$8, "
  "\"launch_height_min\"=$9, "
  "\"launch_height_max\"=$10, "
  "\"launch_distance_min\"=$11, "
  "\"launch_distance_max\"=$12, "
  "\"launch_angle\"=$13, "
  "\"launch_method\"=$14, "
  "\"approve_attack_target_type\"=$15, "
  "\"killing_dose\"=$16, "
  "\"killing_method\"=$17, "
  "\"killing_depth\"=$18, "
  "\"killing_range_min\"=$19, "
  "\"killing_range_max\"=$20, "
  "\"recordcreation_time\"=$21, "
  "\"image_url\"=$22, "
  "\"image_name\"=$23 "
  "WHERE \"id\"=$24";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::erase_statement[] =
  "DELETE FROM \"uav_type_man\".\"ammo_parameters\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::query_statement[] =
  "SELECT "
  "\"uav_type_man\".\"ammo_parameters\".\"id\", "
  "\"uav_type_man\".\"ammo_parameters\".\"ammo_type\", "
  "\"uav_type_man\".\"ammo_parameters\".\"ammo_name\", "
  "\"uav_type_man\".\"ammo_parameters\".\"ammo_id\", "
  "\"uav_type_man\".\"ammo_parameters\".\"ammo_to_uavmodel\", "
  "\"uav_type_man\".\"ammo_parameters\".\"length\", "
  "\"uav_type_man\".\"ammo_parameters\".\"width\", "
  "\"uav_type_man\".\"ammo_parameters\".\"weight\", "
  "\"uav_type_man\".\"ammo_parameters\".\"guidance_type\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_height_min\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_height_max\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_distance_min\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_distance_max\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_angle\", "
  "\"uav_type_man\".\"ammo_parameters\".\"launch_method\", "
  "\"uav_type_man\".\"ammo_parameters\".\"approve_attack_target_type\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_dose\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_method\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_depth\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_range_min\", "
  "\"uav_type_man\".\"ammo_parameters\".\"killing_range_max\", "
  "\"uav_type_man\".\"ammo_parameters\".\"recordcreation_time\", "
  "\"uav_type_man\".\"ammo_parameters\".\"image_url\", "
  "\"uav_type_man\".\"ammo_parameters\".\"image_name\" "
  "FROM \"uav_type_man\".\"ammo_parameters\"";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"uav_type_man\".\"ammo_parameters\"";

  const char access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::table_name[] =
  "\"uav_type_man\".\"ammo_parameters\"";

  void access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::pointer_type
  access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::object_type >
  access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::AmmunitionEntity, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
