/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "uav_type_man"."ammo_approve_attack_target_type" CASCADE;

CREATE TABLE "uav_type_man"."ammo_approve_attack_target_type" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "ammo_attack_target_code" TEXT NOT NULL,
  "ammo_attack_target_name" TEXT NOT NULL,
  "status" BOOLEAN NOT NULL);

