/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "uav_type_man"."ammo_type" CASCADE;

CREATE TABLE "uav_type_man"."ammo_type" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "ammo_type_code" TEXT NOT NULL,
  "ammo_type_name" TEXT NOT NULL,
  "status" BOOLEAN NOT NULL);

