/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "uav_type_man"."ammo_killing_way" CASCADE;

CREATE TABLE "uav_type_man"."ammo_killing_way" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "killing_way_code" TEXT NOT NULL,
  "killing_way_name" TEXT NOT NULL,
  "status" BOOLEAN NOT NULL);

