/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "uav_type_man"."interference_pod" CASCADE;

CREATE TABLE "uav_type_man"."interference_pod" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "interference_pod_name" varchar(100) NOT NULL,
  "interference_pod_type" varchar(50) NOT NULL,
  "interference_pod_id" varchar(50) NOT NULL,
  "used_uav_models" varchar(200) NOT NULL,
  "description" text NOT NULL,
  "main_length" real NOT NULL,
  "interference_length" real NOT NULL,
  "mass" real NOT NULL,
  "front_cover_length" real NOT NULL,
  "rear_cover_length" real NOT NULL,
  "main_cabin_section" real NOT NULL,
  "maximum_weight_pod_fully_loaded" real NOT NULL,
  "interference_band" varchar(100) NOT NULL,
  "effective_reflection_area" varchar(100) NOT NULL,
  "delivery_control_way" varchar(100) NOT NULL,
  "delivery_way" varchar(25) NOT NULL,
  "delivery_speed" varchar(100) NOT NULL,
  "loading_capacity" real NOT NULL,
  "interference_intensity" varchar(100) NOT NULL,
  "image_name" BYTEA NOT NULL,
  "image_url" varchar(50) NOT NULL,
  "record_creation_time" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "use_status" bool NOT NULL);

