// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef INTERFERENCE_POD_ENTITY_ODB_HXX
#define INTERFERENCE_POD_ENTITY_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "InterferencePodEntity.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // InterferencePodEntity
  //
  template <>
  struct class_traits< ::InterferencePodEntity >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::InterferencePodEntity >
  {
    public:
    typedef ::InterferencePodEntity object_type;
    typedef ::InterferencePodEntity* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // InterferencePodEntity
  //
  template <typename A>
  struct query_columns< ::InterferencePodEntity, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // interferencePodName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    interferencePodName_type_;

    static const interferencePodName_type_ interferencePodName;

    // interferencePodType
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    interferencePodType_type_;

    static const interferencePodType_type_ interferencePodType;

    // interferencePodId
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    interferencePodId_type_;

    static const interferencePodId_type_ interferencePodId;

    // usedUavModels
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    usedUavModels_type_;

    static const usedUavModels_type_ usedUavModels;

    // description
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    description_type_;

    static const description_type_ description;

    // mainLength
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    mainLength_type_;

    static const mainLength_type_ mainLength;

    // mass
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    mass_type_;

    static const mass_type_ mass;

    // frontCoverLength
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    frontCoverLength_type_;

    static const frontCoverLength_type_ frontCoverLength;

    // rearCoverLength
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    rearCoverLength_type_;

    static const rearCoverLength_type_ rearCoverLength;

    // mainCabinSection
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    mainCabinSection_type_;

    static const mainCabinSection_type_ mainCabinSection;

    // maximumWeightPodFullyLoaded
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    maximumWeightPodFullyLoaded_type_;

    static const maximumWeightPodFullyLoaded_type_ maximumWeightPodFullyLoaded;

    // interferenceBand
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    interferenceBand_type_;

    static const interferenceBand_type_ interferenceBand;

    // effectiveReflectionArea
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    effectiveReflectionArea_type_;

    static const effectiveReflectionArea_type_ effectiveReflectionArea;

    // deliveryControlWay
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    deliveryControlWay_type_;

    static const deliveryControlWay_type_ deliveryControlWay;

    // deliverySpeed
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    deliverySpeed_type_;

    static const deliverySpeed_type_ deliverySpeed;

    // loadingCapacity
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    loadingCapacity_type_;

    static const loadingCapacity_type_ loadingCapacity;

    // interferenceIntensity
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    interferenceIntensity_type_;

    static const interferenceIntensity_type_ interferenceIntensity;

    // imageName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    imageName_type_;

    static const imageName_type_ imageName;

    // imageUrl
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    imageUrl_type_;

    static const imageUrl_type_ imageUrl;

    // recordCreationTime
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::QDateTime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    recordCreationTime_type_;

    static const recordCreationTime_type_ recordCreationTime;

    // useStatus
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    useStatus_type_;

    static const useStatus_type_ useStatus;
  };

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::id_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::interferencePodName_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  interferencePodName (A::table_name, "\"interference_pod_name\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::interferencePodType_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  interferencePodType (A::table_name, "\"interference_pod_type\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::interferencePodId_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  interferencePodId (A::table_name, "\"interference_pod_id\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::usedUavModels_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  usedUavModels (A::table_name, "\"used_uav_models\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::description_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  description (A::table_name, "\"description\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::mainLength_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  mainLength (A::table_name, "\"main_length\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::mass_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  mass (A::table_name, "\"mass\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::frontCoverLength_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  frontCoverLength (A::table_name, "\"front_cover_length\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::rearCoverLength_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  rearCoverLength (A::table_name, "\"rear_cover_length\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::mainCabinSection_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  mainCabinSection (A::table_name, "\"main_cabin_section\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::maximumWeightPodFullyLoaded_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  maximumWeightPodFullyLoaded (A::table_name, "\"maximum_weight_pod_fully_loaded\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::interferenceBand_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  interferenceBand (A::table_name, "\"interference_band\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::effectiveReflectionArea_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  effectiveReflectionArea (A::table_name, "\"effective_reflection_area\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::deliveryControlWay_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  deliveryControlWay (A::table_name, "\"delivery_control_way\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::deliverySpeed_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  deliverySpeed (A::table_name, "\"delivery_speed\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::loadingCapacity_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  loadingCapacity (A::table_name, "\"loading_capacity\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::interferenceIntensity_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  interferenceIntensity (A::table_name, "\"interference_intensity\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::imageName_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  imageName (A::table_name, "\"image_name\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::imageUrl_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  imageUrl (A::table_name, "\"image_url\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::recordCreationTime_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  recordCreationTime (A::table_name, "\"record_creation_time\"", 0);

  template <typename A>
  const typename query_columns< ::InterferencePodEntity, id_pgsql, A >::useStatus_type_
  query_columns< ::InterferencePodEntity, id_pgsql, A >::
  useStatus (A::table_name, "\"use_status\"", 0);

  template <typename A>
  struct pointer_query_columns< ::InterferencePodEntity, id_pgsql, A >:
    query_columns< ::InterferencePodEntity, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::InterferencePodEntity, id_pgsql >:
    public access::object_traits< ::InterferencePodEntity >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // interferencePodName_
      //
      details::buffer interferencePodName_value;
      std::size_t interferencePodName_size;
      bool interferencePodName_null;

      // interferencePodType_
      //
      details::buffer interferencePodType_value;
      std::size_t interferencePodType_size;
      bool interferencePodType_null;

      // interferencePodId_
      //
      details::buffer interferencePodId_value;
      std::size_t interferencePodId_size;
      bool interferencePodId_null;

      // usedUavModels_
      //
      details::buffer usedUavModels_value;
      std::size_t usedUavModels_size;
      bool usedUavModels_null;

      // description_
      //
      details::buffer description_value;
      std::size_t description_size;
      bool description_null;

      // mainLength_
      //
      float mainLength_value;
      bool mainLength_null;

      // mass_
      //
      float mass_value;
      bool mass_null;

      // frontCoverLength_
      //
      float frontCoverLength_value;
      bool frontCoverLength_null;

      // rearCoverLength_
      //
      float rearCoverLength_value;
      bool rearCoverLength_null;

      // mainCabinSection_
      //
      float mainCabinSection_value;
      bool mainCabinSection_null;

      // maximumWeightPodFullyLoaded_
      //
      float maximumWeightPodFullyLoaded_value;
      bool maximumWeightPodFullyLoaded_null;

      // interferenceBand_
      //
      details::buffer interferenceBand_value;
      std::size_t interferenceBand_size;
      bool interferenceBand_null;

      // effectiveReflectionArea_
      //
      details::buffer effectiveReflectionArea_value;
      std::size_t effectiveReflectionArea_size;
      bool effectiveReflectionArea_null;

      // deliveryControlWay_
      //
      details::buffer deliveryControlWay_value;
      std::size_t deliveryControlWay_size;
      bool deliveryControlWay_null;

      // deliverySpeed_
      //
      details::buffer deliverySpeed_value;
      std::size_t deliverySpeed_size;
      bool deliverySpeed_null;

      // loadingCapacity_
      //
      float loadingCapacity_value;
      bool loadingCapacity_null;

      // interferenceIntensity_
      //
      details::buffer interferenceIntensity_value;
      std::size_t interferenceIntensity_size;
      bool interferenceIntensity_null;

      // imageName_
      //
      details::buffer imageName_value;
      std::size_t imageName_size;
      bool imageName_null;

      // imageUrl_
      //
      details::buffer imageUrl_value;
      std::size_t imageUrl_size;
      bool imageUrl_null;

      // recordCreationTime_
      //
      unsigned long long recordCreationTime_value;
      bool recordCreationTime_null;

      // useStatus_
      //
      bool useStatus_value;
      bool useStatus_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 22UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::InterferencePodEntity, id_common >:
    public access::object_traits_impl< ::InterferencePodEntity, id_pgsql >
  {
  };

  // InterferencePodEntity
  //
}

#include "InterferencePodEntity-odb.ixx"

#include <odb/post.hxx>

#endif // INTERFERENCE_POD_ENTITY_ODB_HXX
