// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "InterferencePodEntity-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/view-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>
#include <odb/pgsql/view-result.hxx>

namespace odb
{
  // InterferencePodEntity
  //

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  persist_statement_name[] = "persist_InterferencePodEntity";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  find_statement_name[] = "find_InterferencePodEntity";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  update_statement_name[] = "update_InterferencePodEntity";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  erase_statement_name[] = "erase_InterferencePodEntity";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  query_statement_name[] = "query_InterferencePodEntity";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  erase_query_statement_name[] = "erase_query_InterferencePodEntity";

  const unsigned int access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::bytea_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::bool_oid
  };

  const unsigned int access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::bytea_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::bool_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::id_type
  access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::id_type
  access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // interferencePodName_
    //
    if (t[1UL])
    {
      i.interferencePodName_value.capacity (i.interferencePodName_size);
      grew = true;
    }

    // interferencePodType_
    //
    if (t[2UL])
    {
      i.interferencePodType_value.capacity (i.interferencePodType_size);
      grew = true;
    }

    // interferencePodId_
    //
    if (t[3UL])
    {
      i.interferencePodId_value.capacity (i.interferencePodId_size);
      grew = true;
    }

    // usedUavModels_
    //
    if (t[4UL])
    {
      i.usedUavModels_value.capacity (i.usedUavModels_size);
      grew = true;
    }

    // description_
    //
    if (t[5UL])
    {
      i.description_value.capacity (i.description_size);
      grew = true;
    }

    // mainLength_
    //
    t[6UL] = 0;

    // interferenceLength_
    //
    t[7UL] = 0;

    // mass_
    //
    t[8UL] = 0;

    // frontCoverLength_
    //
    t[9UL] = 0;

    // rearCoverLength_
    //
    t[10UL] = 0;

    // mainCabinSection_
    //
    t[11UL] = 0;

    // maximumWeightPodFullyLoaded_
    //
    t[12UL] = 0;

    // interferenceBand_
    //
    if (t[13UL])
    {
      i.interferenceBand_value.capacity (i.interferenceBand_size);
      grew = true;
    }

    // effectiveReflectionArea_
    //
    if (t[14UL])
    {
      i.effectiveReflectionArea_value.capacity (i.effectiveReflectionArea_size);
      grew = true;
    }

    // deliveryControlWay_
    //
    if (t[15UL])
    {
      i.deliveryControlWay_value.capacity (i.deliveryControlWay_size);
      grew = true;
    }

    // deliverySpeed_
    //
    if (t[16UL])
    {
      i.deliverySpeed_value.capacity (i.deliverySpeed_size);
      grew = true;
    }

    // loadingCapacity_
    //
    t[17UL] = 0;

    // interferenceIntensity_
    //
    if (t[18UL])
    {
      i.interferenceIntensity_value.capacity (i.interferenceIntensity_size);
      grew = true;
    }

    // imageName_
    //
    if (t[19UL])
    {
      i.imageName_value.capacity (i.imageName_size);
      grew = true;
    }

    // imageUrl_
    //
    if (t[20UL])
    {
      i.imageUrl_value.capacity (i.imageUrl_size);
      grew = true;
    }

    // recordCreationTime_
    //
    t[21UL] = 0;

    // useStatus_
    //
    t[22UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // interferencePodName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.interferencePodName_value.data ();
    b[n].capacity = i.interferencePodName_value.capacity ();
    b[n].size = &i.interferencePodName_size;
    b[n].is_null = &i.interferencePodName_null;
    n++;

    // interferencePodType_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.interferencePodType_value.data ();
    b[n].capacity = i.interferencePodType_value.capacity ();
    b[n].size = &i.interferencePodType_size;
    b[n].is_null = &i.interferencePodType_null;
    n++;

    // interferencePodId_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.interferencePodId_value.data ();
    b[n].capacity = i.interferencePodId_value.capacity ();
    b[n].size = &i.interferencePodId_size;
    b[n].is_null = &i.interferencePodId_null;
    n++;

    // usedUavModels_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.usedUavModels_value.data ();
    b[n].capacity = i.usedUavModels_value.capacity ();
    b[n].size = &i.usedUavModels_size;
    b[n].is_null = &i.usedUavModels_null;
    n++;

    // description_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.description_value.data ();
    b[n].capacity = i.description_value.capacity ();
    b[n].size = &i.description_size;
    b[n].is_null = &i.description_null;
    n++;

    // mainLength_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.mainLength_value;
    b[n].is_null = &i.mainLength_null;
    n++;

    // interferenceLength_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.interferenceLength_value;
    b[n].is_null = &i.interferenceLength_null;
    n++;

    // mass_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.mass_value;
    b[n].is_null = &i.mass_null;
    n++;

    // frontCoverLength_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.frontCoverLength_value;
    b[n].is_null = &i.frontCoverLength_null;
    n++;

    // rearCoverLength_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.rearCoverLength_value;
    b[n].is_null = &i.rearCoverLength_null;
    n++;

    // mainCabinSection_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.mainCabinSection_value;
    b[n].is_null = &i.mainCabinSection_null;
    n++;

    // maximumWeightPodFullyLoaded_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.maximumWeightPodFullyLoaded_value;
    b[n].is_null = &i.maximumWeightPodFullyLoaded_null;
    n++;

    // interferenceBand_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.interferenceBand_value.data ();
    b[n].capacity = i.interferenceBand_value.capacity ();
    b[n].size = &i.interferenceBand_size;
    b[n].is_null = &i.interferenceBand_null;
    n++;

    // effectiveReflectionArea_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.effectiveReflectionArea_value.data ();
    b[n].capacity = i.effectiveReflectionArea_value.capacity ();
    b[n].size = &i.effectiveReflectionArea_size;
    b[n].is_null = &i.effectiveReflectionArea_null;
    n++;

    // deliveryControlWay_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.deliveryControlWay_value.data ();
    b[n].capacity = i.deliveryControlWay_value.capacity ();
    b[n].size = &i.deliveryControlWay_size;
    b[n].is_null = &i.deliveryControlWay_null;
    n++;

    // deliverySpeed_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.deliverySpeed_value.data ();
    b[n].capacity = i.deliverySpeed_value.capacity ();
    b[n].size = &i.deliverySpeed_size;
    b[n].is_null = &i.deliverySpeed_null;
    n++;

    // loadingCapacity_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.loadingCapacity_value;
    b[n].is_null = &i.loadingCapacity_null;
    n++;

    // interferenceIntensity_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.interferenceIntensity_value.data ();
    b[n].capacity = i.interferenceIntensity_value.capacity ();
    b[n].size = &i.interferenceIntensity_size;
    b[n].is_null = &i.interferenceIntensity_null;
    n++;

    // imageName_
    //
    b[n].type = pgsql::bind::bytea;
    b[n].buffer = i.imageName_value.data ();
    b[n].capacity = i.imageName_value.capacity ();
    b[n].size = &i.imageName_size;
    b[n].is_null = &i.imageName_null;
    n++;

    // imageUrl_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.imageUrl_value.data ();
    b[n].capacity = i.imageUrl_value.capacity ();
    b[n].size = &i.imageUrl_size;
    b[n].is_null = &i.imageUrl_null;
    n++;

    // recordCreationTime_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.recordCreationTime_value;
    b[n].is_null = &i.recordCreationTime_null;
    n++;

    // useStatus_
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.useStatus_value;
    b[n].is_null = &i.useStatus_null;
    n++;
  }

  void access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // interferencePodName_
    //
    {
      ::std::string const& v =
        o.interferencePodName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.interferencePodName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.interferencePodName_value,
        size,
        is_null,
        v);
      i.interferencePodName_null = is_null;
      i.interferencePodName_size = size;
      grew = grew || (cap != i.interferencePodName_value.capacity ());
    }

    // interferencePodType_
    //
    {
      ::std::string const& v =
        o.interferencePodType_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.interferencePodType_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.interferencePodType_value,
        size,
        is_null,
        v);
      i.interferencePodType_null = is_null;
      i.interferencePodType_size = size;
      grew = grew || (cap != i.interferencePodType_value.capacity ());
    }

    // interferencePodId_
    //
    {
      ::std::string const& v =
        o.interferencePodId_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.interferencePodId_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.interferencePodId_value,
        size,
        is_null,
        v);
      i.interferencePodId_null = is_null;
      i.interferencePodId_size = size;
      grew = grew || (cap != i.interferencePodId_value.capacity ());
    }

    // usedUavModels_
    //
    {
      ::std::string const& v =
        o.usedUavModels_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.usedUavModels_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.usedUavModels_value,
        size,
        is_null,
        v);
      i.usedUavModels_null = is_null;
      i.usedUavModels_size = size;
      grew = grew || (cap != i.usedUavModels_value.capacity ());
    }

    // description_
    //
    {
      ::std::string const& v =
        o.description_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.description_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.description_value,
        size,
        is_null,
        v);
      i.description_null = is_null;
      i.description_size = size;
      grew = grew || (cap != i.description_value.capacity ());
    }

    // mainLength_
    //
    {
      float const& v =
        o.mainLength_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.mainLength_value, is_null, v);
      i.mainLength_null = is_null;
    }

    // interferenceLength_
    //
    {
      float const& v =
        o.interferenceLength_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.interferenceLength_value, is_null, v);
      i.interferenceLength_null = is_null;
    }

    // mass_
    //
    {
      float const& v =
        o.mass_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.mass_value, is_null, v);
      i.mass_null = is_null;
    }

    // frontCoverLength_
    //
    {
      float const& v =
        o.frontCoverLength_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.frontCoverLength_value, is_null, v);
      i.frontCoverLength_null = is_null;
    }

    // rearCoverLength_
    //
    {
      float const& v =
        o.rearCoverLength_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.rearCoverLength_value, is_null, v);
      i.rearCoverLength_null = is_null;
    }

    // mainCabinSection_
    //
    {
      float const& v =
        o.mainCabinSection_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.mainCabinSection_value, is_null, v);
      i.mainCabinSection_null = is_null;
    }

    // maximumWeightPodFullyLoaded_
    //
    {
      float const& v =
        o.maximumWeightPodFullyLoaded_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.maximumWeightPodFullyLoaded_value, is_null, v);
      i.maximumWeightPodFullyLoaded_null = is_null;
    }

    // interferenceBand_
    //
    {
      ::std::string const& v =
        o.interferenceBand_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.interferenceBand_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.interferenceBand_value,
        size,
        is_null,
        v);
      i.interferenceBand_null = is_null;
      i.interferenceBand_size = size;
      grew = grew || (cap != i.interferenceBand_value.capacity ());
    }

    // effectiveReflectionArea_
    //
    {
      ::std::string const& v =
        o.effectiveReflectionArea_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.effectiveReflectionArea_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.effectiveReflectionArea_value,
        size,
        is_null,
        v);
      i.effectiveReflectionArea_null = is_null;
      i.effectiveReflectionArea_size = size;
      grew = grew || (cap != i.effectiveReflectionArea_value.capacity ());
    }

    // deliveryControlWay_
    //
    {
      ::std::string const& v =
        o.deliveryControlWay_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.deliveryControlWay_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.deliveryControlWay_value,
        size,
        is_null,
        v);
      i.deliveryControlWay_null = is_null;
      i.deliveryControlWay_size = size;
      grew = grew || (cap != i.deliveryControlWay_value.capacity ());
    }

    // deliverySpeed_
    //
    {
      ::std::string const& v =
        o.deliverySpeed_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.deliverySpeed_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.deliverySpeed_value,
        size,
        is_null,
        v);
      i.deliverySpeed_null = is_null;
      i.deliverySpeed_size = size;
      grew = grew || (cap != i.deliverySpeed_value.capacity ());
    }

    // loadingCapacity_
    //
    {
      float const& v =
        o.loadingCapacity_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.loadingCapacity_value, is_null, v);
      i.loadingCapacity_null = is_null;
    }

    // interferenceIntensity_
    //
    {
      ::std::string const& v =
        o.interferenceIntensity_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.interferenceIntensity_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.interferenceIntensity_value,
        size,
        is_null,
        v);
      i.interferenceIntensity_null = is_null;
      i.interferenceIntensity_size = size;
      grew = grew || (cap != i.interferenceIntensity_value.capacity ());
    }

    // imageName_
    //
    {
      ::std::vector< char > const& v =
        o.imageName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.imageName_value.capacity ());
      pgsql::value_traits<
          ::std::vector< char >,
          pgsql::id_bytea >::set_image (
        i.imageName_value,
        size,
        is_null,
        v);
      i.imageName_null = is_null;
      i.imageName_size = size;
      grew = grew || (cap != i.imageName_value.capacity ());
    }

    // imageUrl_
    //
    {
      ::std::string const& v =
        o.imageUrl_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.imageUrl_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.imageUrl_value,
        size,
        is_null,
        v);
      i.imageUrl_null = is_null;
      i.imageUrl_size = size;
      grew = grew || (cap != i.imageUrl_value.capacity ());
    }

    // recordCreationTime_
    //
    {
      ::QDateTime const& v =
        o.recordCreationTime_;

      bool is_null (false);
      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_image (
        i.recordCreationTime_value, is_null, v);
      i.recordCreationTime_null = is_null;
    }

    // useStatus_
    //
    {
      bool const& v =
        o.useStatus_;

      bool is_null (false);
      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.useStatus_value, is_null, v);
      i.useStatus_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      long int& v =
        o.id_;

      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // interferencePodName_
    //
    {
      ::std::string& v =
        o.interferencePodName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.interferencePodName_value,
        i.interferencePodName_size,
        i.interferencePodName_null);
    }

    // interferencePodType_
    //
    {
      ::std::string& v =
        o.interferencePodType_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.interferencePodType_value,
        i.interferencePodType_size,
        i.interferencePodType_null);
    }

    // interferencePodId_
    //
    {
      ::std::string& v =
        o.interferencePodId_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.interferencePodId_value,
        i.interferencePodId_size,
        i.interferencePodId_null);
    }

    // usedUavModels_
    //
    {
      ::std::string& v =
        o.usedUavModels_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.usedUavModels_value,
        i.usedUavModels_size,
        i.usedUavModels_null);
    }

    // description_
    //
    {
      ::std::string& v =
        o.description_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.description_value,
        i.description_size,
        i.description_null);
    }

    // mainLength_
    //
    {
      float& v =
        o.mainLength_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.mainLength_value,
        i.mainLength_null);
    }

    // interferenceLength_
    //
    {
      float& v =
        o.interferenceLength_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.interferenceLength_value,
        i.interferenceLength_null);
    }

    // mass_
    //
    {
      float& v =
        o.mass_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.mass_value,
        i.mass_null);
    }

    // frontCoverLength_
    //
    {
      float& v =
        o.frontCoverLength_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.frontCoverLength_value,
        i.frontCoverLength_null);
    }

    // rearCoverLength_
    //
    {
      float& v =
        o.rearCoverLength_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.rearCoverLength_value,
        i.rearCoverLength_null);
    }

    // mainCabinSection_
    //
    {
      float& v =
        o.mainCabinSection_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.mainCabinSection_value,
        i.mainCabinSection_null);
    }

    // maximumWeightPodFullyLoaded_
    //
    {
      float& v =
        o.maximumWeightPodFullyLoaded_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.maximumWeightPodFullyLoaded_value,
        i.maximumWeightPodFullyLoaded_null);
    }

    // interferenceBand_
    //
    {
      ::std::string& v =
        o.interferenceBand_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.interferenceBand_value,
        i.interferenceBand_size,
        i.interferenceBand_null);
    }

    // effectiveReflectionArea_
    //
    {
      ::std::string& v =
        o.effectiveReflectionArea_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.effectiveReflectionArea_value,
        i.effectiveReflectionArea_size,
        i.effectiveReflectionArea_null);
    }

    // deliveryControlWay_
    //
    {
      ::std::string& v =
        o.deliveryControlWay_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.deliveryControlWay_value,
        i.deliveryControlWay_size,
        i.deliveryControlWay_null);
    }

    // deliverySpeed_
    //
    {
      ::std::string& v =
        o.deliverySpeed_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.deliverySpeed_value,
        i.deliverySpeed_size,
        i.deliverySpeed_null);
    }

    // loadingCapacity_
    //
    {
      float& v =
        o.loadingCapacity_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.loadingCapacity_value,
        i.loadingCapacity_null);
    }

    // interferenceIntensity_
    //
    {
      ::std::string& v =
        o.interferenceIntensity_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.interferenceIntensity_value,
        i.interferenceIntensity_size,
        i.interferenceIntensity_null);
    }

    // imageName_
    //
    {
      ::std::vector< char >& v =
        o.imageName_;

      pgsql::value_traits<
          ::std::vector< char >,
          pgsql::id_bytea >::set_value (
        v,
        i.imageName_value,
        i.imageName_size,
        i.imageName_null);
    }

    // imageUrl_
    //
    {
      ::std::string& v =
        o.imageUrl_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.imageUrl_value,
        i.imageUrl_size,
        i.imageUrl_null);
    }

    // recordCreationTime_
    //
    {
      ::QDateTime& v =
        o.recordCreationTime_;

      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_value (
        v,
        i.recordCreationTime_value,
        i.recordCreationTime_null);
    }

    // useStatus_
    //
    {
      bool& v =
        o.useStatus_;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.useStatus_value,
        i.useStatus_null);
    }
  }

  void access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::persist_statement[] =
  "INSERT INTO \"uav_type_man\".\"interference_pod\" "
  "(\"id\", "
  "\"interference_pod_name\", "
  "\"interference_pod_type\", "
  "\"interference_pod_id\", "
  "\"used_uav_models\", "
  "\"description\", "
  "\"main_length\", "
  "\"interference_length\", "
  "\"mass\", "
  "\"front_cover_length\", "
  "\"rear_cover_length\", "
  "\"main_cabin_section\", "
  "\"maximum_weight_pod_fully_loaded\", "
  "\"interference_band\", "
  "\"effective_reflection_area\", "
  "\"delivery_control_way\", "
  "\"delivery_speed\", "
  "\"loading_capacity\", "
  "\"interference_intensity\", "
  "\"image_name\", "
  "\"image_url\", "
  "\"record_creation_time\", "
  "\"use_status\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::find_statement[] =
  "SELECT "
  "\"uav_type_man\".\"interference_pod\".\"id\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_pod_name\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_pod_type\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_pod_id\", "
  "\"uav_type_man\".\"interference_pod\".\"used_uav_models\", "
  "\"uav_type_man\".\"interference_pod\".\"description\", "
  "\"uav_type_man\".\"interference_pod\".\"main_length\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_length\", "
  "\"uav_type_man\".\"interference_pod\".\"mass\", "
  "\"uav_type_man\".\"interference_pod\".\"front_cover_length\", "
  "\"uav_type_man\".\"interference_pod\".\"rear_cover_length\", "
  "\"uav_type_man\".\"interference_pod\".\"main_cabin_section\", "
  "\"uav_type_man\".\"interference_pod\".\"maximum_weight_pod_fully_loaded\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_band\", "
  "\"uav_type_man\".\"interference_pod\".\"effective_reflection_area\", "
  "\"uav_type_man\".\"interference_pod\".\"delivery_control_way\", "
  "\"uav_type_man\".\"interference_pod\".\"delivery_speed\", "
  "\"uav_type_man\".\"interference_pod\".\"loading_capacity\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_intensity\", "
  "\"uav_type_man\".\"interference_pod\".\"image_name\", "
  "\"uav_type_man\".\"interference_pod\".\"image_url\", "
  "\"uav_type_man\".\"interference_pod\".\"record_creation_time\", "
  "\"uav_type_man\".\"interference_pod\".\"use_status\" "
  "FROM \"uav_type_man\".\"interference_pod\" "
  "WHERE \"uav_type_man\".\"interference_pod\".\"id\"=$1";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::update_statement[] =
  "UPDATE \"uav_type_man\".\"interference_pod\" "
  "SET "
  "\"interference_pod_name\"=$1, "
  "\"interference_pod_type\"=$2, "
  "\"interference_pod_id\"=$3, "
  "\"used_uav_models\"=$4, "
  "\"description\"=$5, "
  "\"main_length\"=$6, "
  "\"interference_length\"=$7, "
  "\"mass\"=$8, "
  "\"front_cover_length\"=$9, "
  "\"rear_cover_length\"=$10, "
  "\"main_cabin_section\"=$11, "
  "\"maximum_weight_pod_fully_loaded\"=$12, "
  "\"interference_band\"=$13, "
  "\"effective_reflection_area\"=$14, "
  "\"delivery_control_way\"=$15, "
  "\"delivery_speed\"=$16, "
  "\"loading_capacity\"=$17, "
  "\"interference_intensity\"=$18, "
  "\"image_name\"=$19, "
  "\"image_url\"=$20, "
  "\"record_creation_time\"=$21, "
  "\"use_status\"=$22 "
  "WHERE \"id\"=$23";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::erase_statement[] =
  "DELETE FROM \"uav_type_man\".\"interference_pod\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::query_statement[] =
  "SELECT "
  "\"uav_type_man\".\"interference_pod\".\"id\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_pod_name\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_pod_type\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_pod_id\", "
  "\"uav_type_man\".\"interference_pod\".\"used_uav_models\", "
  "\"uav_type_man\".\"interference_pod\".\"description\", "
  "\"uav_type_man\".\"interference_pod\".\"main_length\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_length\", "
  "\"uav_type_man\".\"interference_pod\".\"mass\", "
  "\"uav_type_man\".\"interference_pod\".\"front_cover_length\", "
  "\"uav_type_man\".\"interference_pod\".\"rear_cover_length\", "
  "\"uav_type_man\".\"interference_pod\".\"main_cabin_section\", "
  "\"uav_type_man\".\"interference_pod\".\"maximum_weight_pod_fully_loaded\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_band\", "
  "\"uav_type_man\".\"interference_pod\".\"effective_reflection_area\", "
  "\"uav_type_man\".\"interference_pod\".\"delivery_control_way\", "
  "\"uav_type_man\".\"interference_pod\".\"delivery_speed\", "
  "\"uav_type_man\".\"interference_pod\".\"loading_capacity\", "
  "\"uav_type_man\".\"interference_pod\".\"interference_intensity\", "
  "\"uav_type_man\".\"interference_pod\".\"image_name\", "
  "\"uav_type_man\".\"interference_pod\".\"image_url\", "
  "\"uav_type_man\".\"interference_pod\".\"record_creation_time\", "
  "\"uav_type_man\".\"interference_pod\".\"use_status\" "
  "FROM \"uav_type_man\".\"interference_pod\"";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"uav_type_man\".\"interference_pod\"";

  const char access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::table_name[] =
  "\"uav_type_man\".\"interference_pod\"";

  void access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::pointer_type
  access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::object_type >
  access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::InterferencePodEntity, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }

  // dummy
  //

  const char access::view_traits_impl< ::view::dummy, id_pgsql >::
  query_statement_name[] = "query_view_dummy";

  bool access::view_traits_impl< ::view::dummy, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // value
    //
    t[0UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::view::dummy, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // value
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.value_value;
    b[n].is_null = &i.value_null;
    n++;
  }

  void access::view_traits_impl< ::view::dummy, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      ::std::size_t& v =
        o.value;

      pgsql::value_traits<
          ::std::size_t,
          pgsql::id_bigint >::set_value (
        v,
        i.value_value,
        i.value_null);
    }
  }

  result< access::view_traits_impl< ::view::dummy, id_pgsql >::view_type >
  access::view_traits_impl< ::view::dummy, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (q);
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }

  // string
  //

  const char access::view_traits_impl< ::view::string, id_pgsql >::
  query_statement_name[] = "query_view_string";

  bool access::view_traits_impl< ::view::string, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // value
    //
    if (t[0UL])
    {
      i.value_value.capacity (i.value_size);
      grew = true;
    }

    return grew;
  }

  void access::view_traits_impl< ::view::string, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // value
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.value_value.data ();
    b[n].capacity = i.value_value.capacity ();
    b[n].size = &i.value_size;
    b[n].is_null = &i.value_null;
    n++;
  }

  void access::view_traits_impl< ::view::string, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      ::std::string& v =
        o.value;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.value_value,
        i.value_size,
        i.value_null);
    }
  }

  result< access::view_traits_impl< ::view::string, id_pgsql >::view_type >
  access::view_traits_impl< ::view::string, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (q);
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }
}

#include <odb/post.hxx>
