// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "MountingSchemeEntity-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // UavMountSchemeEntity
  //

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  persist_statement_name[] = "persist_UavMountSchemeEntity";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  find_statement_name[] = "find_UavMountSchemeEntity";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  update_statement_name[] = "update_UavMountSchemeEntity";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  erase_statement_name[] = "erase_UavMountSchemeEntity";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  query_statement_name[] = "query_UavMountSchemeEntity";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  erase_query_statement_name[] = "erase_query_UavMountSchemeEntity";

  const unsigned int access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::timestamp_oid,
    pgsql::bool_oid
  };

  const unsigned int access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::timestamp_oid,
    pgsql::bool_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::id_type
  access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::id_type
  access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // mountSchemeName_
    //
    if (t[1UL])
    {
      i.mountSchemeName_value.capacity (i.mountSchemeName_size);
      grew = true;
    }

    // uavName_
    //
    if (t[2UL])
    {
      i.uavName_value.capacity (i.uavName_size);
      grew = true;
    }

    // maxTakeoffWeight_
    //
    t[3UL] = 0;

    // emptyWeight_
    //
    t[4UL] = 0;

    // oneHangingPoint_
    //
    if (t[5UL])
    {
      i.oneHangingPoint_value.capacity (i.oneHangingPoint_size);
      grew = true;
    }

    // oneLocation_
    //
    if (t[6UL])
    {
      i.oneLocation_value.capacity (i.oneLocation_size);
      grew = true;
    }

    // oneAmmoName_
    //
    if (t[7UL])
    {
      i.oneAmmoName_value.capacity (i.oneAmmoName_size);
      grew = true;
    }

    // twoHangingPoint_
    //
    if (t[8UL])
    {
      i.twoHangingPoint_value.capacity (i.twoHangingPoint_size);
      grew = true;
    }

    // twoLocation_
    //
    if (t[9UL])
    {
      i.twoLocation_value.capacity (i.twoLocation_size);
      grew = true;
    }

    // twoAmmoName_
    //
    if (t[10UL])
    {
      i.twoAmmoName_value.capacity (i.twoAmmoName_size);
      grew = true;
    }

    // threeHangingPoint_
    //
    if (t[11UL])
    {
      i.threeHangingPoint_value.capacity (i.threeHangingPoint_size);
      grew = true;
    }

    // threeLocation_
    //
    if (t[12UL])
    {
      i.threeLocation_value.capacity (i.threeLocation_size);
      grew = true;
    }

    // threeAmmoName_
    //
    if (t[13UL])
    {
      i.threeAmmoName_value.capacity (i.threeAmmoName_size);
      grew = true;
    }

    // fourHangingPoint_
    //
    if (t[14UL])
    {
      i.fourHangingPoint_value.capacity (i.fourHangingPoint_size);
      grew = true;
    }

    // fourLocation_
    //
    if (t[15UL])
    {
      i.fourLocation_value.capacity (i.fourLocation_size);
      grew = true;
    }

    // fourAmmoName_
    //
    if (t[16UL])
    {
      i.fourAmmoName_value.capacity (i.fourAmmoName_size);
      grew = true;
    }

    // fiveHangingPoint_
    //
    if (t[17UL])
    {
      i.fiveHangingPoint_value.capacity (i.fiveHangingPoint_size);
      grew = true;
    }

    // fiveLocation_
    //
    if (t[18UL])
    {
      i.fiveLocation_value.capacity (i.fiveLocation_size);
      grew = true;
    }

    // fiveAmmoName_
    //
    if (t[19UL])
    {
      i.fiveAmmoName_value.capacity (i.fiveAmmoName_size);
      grew = true;
    }

    // sixHangingPoint_
    //
    if (t[20UL])
    {
      i.sixHangingPoint_value.capacity (i.sixHangingPoint_size);
      grew = true;
    }

    // sixLocation_
    //
    if (t[21UL])
    {
      i.sixLocation_value.capacity (i.sixLocation_size);
      grew = true;
    }

    // sixAmmoName_
    //
    if (t[22UL])
    {
      i.sixAmmoName_value.capacity (i.sixAmmoName_size);
      grew = true;
    }

    // sevenHangingPoint_
    //
    if (t[23UL])
    {
      i.sevenHangingPoint_value.capacity (i.sevenHangingPoint_size);
      grew = true;
    }

    // sevenLocation_
    //
    if (t[24UL])
    {
      i.sevenLocation_value.capacity (i.sevenLocation_size);
      grew = true;
    }

    // sevenAmmoName_
    //
    if (t[25UL])
    {
      i.sevenAmmoName_value.capacity (i.sevenAmmoName_size);
      grew = true;
    }

    // eightHangingPoint_
    //
    if (t[26UL])
    {
      i.eightHangingPoint_value.capacity (i.eightHangingPoint_size);
      grew = true;
    }

    // eightLocation_
    //
    if (t[27UL])
    {
      i.eightLocation_value.capacity (i.eightLocation_size);
      grew = true;
    }

    // eightAmmoName_
    //
    if (t[28UL])
    {
      i.eightAmmoName_value.capacity (i.eightAmmoName_size);
      grew = true;
    }

    // nineHangingPoint_
    //
    if (t[29UL])
    {
      i.nineHangingPoint_value.capacity (i.nineHangingPoint_size);
      grew = true;
    }

    // nineLocation_
    //
    if (t[30UL])
    {
      i.nineLocation_value.capacity (i.nineLocation_size);
      grew = true;
    }

    // nineAmmoName_
    //
    if (t[31UL])
    {
      i.nineAmmoName_value.capacity (i.nineAmmoName_size);
      grew = true;
    }

    // tenHangingPoint_
    //
    if (t[32UL])
    {
      i.tenHangingPoint_value.capacity (i.tenHangingPoint_size);
      grew = true;
    }

    // tenLocation_
    //
    if (t[33UL])
    {
      i.tenLocation_value.capacity (i.tenLocation_size);
      grew = true;
    }

    // tenAmmoName_
    //
    if (t[34UL])
    {
      i.tenAmmoName_value.capacity (i.tenAmmoName_size);
      grew = true;
    }

    // runningDistance_
    //
    t[35UL] = 0;

    // endurance_
    //
    t[36UL] = 0;

    // fightRadius_
    //
    t[37UL] = 0;

    // maxFuel_
    //
    t[38UL] = 0;

    // maxExternalWeight_
    //
    t[39UL] = 0;

    // recordCreationTime_
    //
    t[40UL] = 0;

    // status_
    //
    t[41UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // mountSchemeName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.mountSchemeName_value.data ();
    b[n].capacity = i.mountSchemeName_value.capacity ();
    b[n].size = &i.mountSchemeName_size;
    b[n].is_null = &i.mountSchemeName_null;
    n++;

    // uavName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.uavName_value.data ();
    b[n].capacity = i.uavName_value.capacity ();
    b[n].size = &i.uavName_size;
    b[n].is_null = &i.uavName_null;
    n++;

    // maxTakeoffWeight_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.maxTakeoffWeight_value;
    b[n].is_null = &i.maxTakeoffWeight_null;
    n++;

    // emptyWeight_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.emptyWeight_value;
    b[n].is_null = &i.emptyWeight_null;
    n++;

    // oneHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.oneHangingPoint_value.data ();
    b[n].capacity = i.oneHangingPoint_value.capacity ();
    b[n].size = &i.oneHangingPoint_size;
    b[n].is_null = &i.oneHangingPoint_null;
    n++;

    // oneLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.oneLocation_value.data ();
    b[n].capacity = i.oneLocation_value.capacity ();
    b[n].size = &i.oneLocation_size;
    b[n].is_null = &i.oneLocation_null;
    n++;

    // oneAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.oneAmmoName_value.data ();
    b[n].capacity = i.oneAmmoName_value.capacity ();
    b[n].size = &i.oneAmmoName_size;
    b[n].is_null = &i.oneAmmoName_null;
    n++;

    // twoHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.twoHangingPoint_value.data ();
    b[n].capacity = i.twoHangingPoint_value.capacity ();
    b[n].size = &i.twoHangingPoint_size;
    b[n].is_null = &i.twoHangingPoint_null;
    n++;

    // twoLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.twoLocation_value.data ();
    b[n].capacity = i.twoLocation_value.capacity ();
    b[n].size = &i.twoLocation_size;
    b[n].is_null = &i.twoLocation_null;
    n++;

    // twoAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.twoAmmoName_value.data ();
    b[n].capacity = i.twoAmmoName_value.capacity ();
    b[n].size = &i.twoAmmoName_size;
    b[n].is_null = &i.twoAmmoName_null;
    n++;

    // threeHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.threeHangingPoint_value.data ();
    b[n].capacity = i.threeHangingPoint_value.capacity ();
    b[n].size = &i.threeHangingPoint_size;
    b[n].is_null = &i.threeHangingPoint_null;
    n++;

    // threeLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.threeLocation_value.data ();
    b[n].capacity = i.threeLocation_value.capacity ();
    b[n].size = &i.threeLocation_size;
    b[n].is_null = &i.threeLocation_null;
    n++;

    // threeAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.threeAmmoName_value.data ();
    b[n].capacity = i.threeAmmoName_value.capacity ();
    b[n].size = &i.threeAmmoName_size;
    b[n].is_null = &i.threeAmmoName_null;
    n++;

    // fourHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.fourHangingPoint_value.data ();
    b[n].capacity = i.fourHangingPoint_value.capacity ();
    b[n].size = &i.fourHangingPoint_size;
    b[n].is_null = &i.fourHangingPoint_null;
    n++;

    // fourLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.fourLocation_value.data ();
    b[n].capacity = i.fourLocation_value.capacity ();
    b[n].size = &i.fourLocation_size;
    b[n].is_null = &i.fourLocation_null;
    n++;

    // fourAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.fourAmmoName_value.data ();
    b[n].capacity = i.fourAmmoName_value.capacity ();
    b[n].size = &i.fourAmmoName_size;
    b[n].is_null = &i.fourAmmoName_null;
    n++;

    // fiveHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.fiveHangingPoint_value.data ();
    b[n].capacity = i.fiveHangingPoint_value.capacity ();
    b[n].size = &i.fiveHangingPoint_size;
    b[n].is_null = &i.fiveHangingPoint_null;
    n++;

    // fiveLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.fiveLocation_value.data ();
    b[n].capacity = i.fiveLocation_value.capacity ();
    b[n].size = &i.fiveLocation_size;
    b[n].is_null = &i.fiveLocation_null;
    n++;

    // fiveAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.fiveAmmoName_value.data ();
    b[n].capacity = i.fiveAmmoName_value.capacity ();
    b[n].size = &i.fiveAmmoName_size;
    b[n].is_null = &i.fiveAmmoName_null;
    n++;

    // sixHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.sixHangingPoint_value.data ();
    b[n].capacity = i.sixHangingPoint_value.capacity ();
    b[n].size = &i.sixHangingPoint_size;
    b[n].is_null = &i.sixHangingPoint_null;
    n++;

    // sixLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.sixLocation_value.data ();
    b[n].capacity = i.sixLocation_value.capacity ();
    b[n].size = &i.sixLocation_size;
    b[n].is_null = &i.sixLocation_null;
    n++;

    // sixAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.sixAmmoName_value.data ();
    b[n].capacity = i.sixAmmoName_value.capacity ();
    b[n].size = &i.sixAmmoName_size;
    b[n].is_null = &i.sixAmmoName_null;
    n++;

    // sevenHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.sevenHangingPoint_value.data ();
    b[n].capacity = i.sevenHangingPoint_value.capacity ();
    b[n].size = &i.sevenHangingPoint_size;
    b[n].is_null = &i.sevenHangingPoint_null;
    n++;

    // sevenLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.sevenLocation_value.data ();
    b[n].capacity = i.sevenLocation_value.capacity ();
    b[n].size = &i.sevenLocation_size;
    b[n].is_null = &i.sevenLocation_null;
    n++;

    // sevenAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.sevenAmmoName_value.data ();
    b[n].capacity = i.sevenAmmoName_value.capacity ();
    b[n].size = &i.sevenAmmoName_size;
    b[n].is_null = &i.sevenAmmoName_null;
    n++;

    // eightHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.eightHangingPoint_value.data ();
    b[n].capacity = i.eightHangingPoint_value.capacity ();
    b[n].size = &i.eightHangingPoint_size;
    b[n].is_null = &i.eightHangingPoint_null;
    n++;

    // eightLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.eightLocation_value.data ();
    b[n].capacity = i.eightLocation_value.capacity ();
    b[n].size = &i.eightLocation_size;
    b[n].is_null = &i.eightLocation_null;
    n++;

    // eightAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.eightAmmoName_value.data ();
    b[n].capacity = i.eightAmmoName_value.capacity ();
    b[n].size = &i.eightAmmoName_size;
    b[n].is_null = &i.eightAmmoName_null;
    n++;

    // nineHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.nineHangingPoint_value.data ();
    b[n].capacity = i.nineHangingPoint_value.capacity ();
    b[n].size = &i.nineHangingPoint_size;
    b[n].is_null = &i.nineHangingPoint_null;
    n++;

    // nineLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.nineLocation_value.data ();
    b[n].capacity = i.nineLocation_value.capacity ();
    b[n].size = &i.nineLocation_size;
    b[n].is_null = &i.nineLocation_null;
    n++;

    // nineAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.nineAmmoName_value.data ();
    b[n].capacity = i.nineAmmoName_value.capacity ();
    b[n].size = &i.nineAmmoName_size;
    b[n].is_null = &i.nineAmmoName_null;
    n++;

    // tenHangingPoint_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.tenHangingPoint_value.data ();
    b[n].capacity = i.tenHangingPoint_value.capacity ();
    b[n].size = &i.tenHangingPoint_size;
    b[n].is_null = &i.tenHangingPoint_null;
    n++;

    // tenLocation_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.tenLocation_value.data ();
    b[n].capacity = i.tenLocation_value.capacity ();
    b[n].size = &i.tenLocation_size;
    b[n].is_null = &i.tenLocation_null;
    n++;

    // tenAmmoName_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.tenAmmoName_value.data ();
    b[n].capacity = i.tenAmmoName_value.capacity ();
    b[n].size = &i.tenAmmoName_size;
    b[n].is_null = &i.tenAmmoName_null;
    n++;

    // runningDistance_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.runningDistance_value;
    b[n].is_null = &i.runningDistance_null;
    n++;

    // endurance_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.endurance_value;
    b[n].is_null = &i.endurance_null;
    n++;

    // fightRadius_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.fightRadius_value;
    b[n].is_null = &i.fightRadius_null;
    n++;

    // maxFuel_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.maxFuel_value;
    b[n].is_null = &i.maxFuel_null;
    n++;

    // maxExternalWeight_
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.maxExternalWeight_value;
    b[n].is_null = &i.maxExternalWeight_null;
    n++;

    // recordCreationTime_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.recordCreationTime_value;
    b[n].is_null = &i.recordCreationTime_null;
    n++;

    // status_
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.status_value;
    b[n].is_null = &i.status_null;
    n++;
  }

  void access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // mountSchemeName_
    //
    {
      ::std::string const& v =
        o.mountSchemeName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.mountSchemeName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.mountSchemeName_value,
        size,
        is_null,
        v);
      i.mountSchemeName_null = is_null;
      i.mountSchemeName_size = size;
      grew = grew || (cap != i.mountSchemeName_value.capacity ());
    }

    // uavName_
    //
    {
      ::std::string const& v =
        o.uavName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.uavName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.uavName_value,
        size,
        is_null,
        v);
      i.uavName_null = is_null;
      i.uavName_size = size;
      grew = grew || (cap != i.uavName_value.capacity ());
    }

    // maxTakeoffWeight_
    //
    {
      float const& v =
        o.maxTakeoffWeight_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.maxTakeoffWeight_value, is_null, v);
      i.maxTakeoffWeight_null = is_null;
    }

    // emptyWeight_
    //
    {
      float const& v =
        o.emptyWeight_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.emptyWeight_value, is_null, v);
      i.emptyWeight_null = is_null;
    }

    // oneHangingPoint_
    //
    {
      ::std::string const& v =
        o.oneHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.oneHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.oneHangingPoint_value,
        size,
        is_null,
        v);
      i.oneHangingPoint_null = is_null;
      i.oneHangingPoint_size = size;
      grew = grew || (cap != i.oneHangingPoint_value.capacity ());
    }

    // oneLocation_
    //
    {
      ::std::string const& v =
        o.oneLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.oneLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.oneLocation_value,
        size,
        is_null,
        v);
      i.oneLocation_null = is_null;
      i.oneLocation_size = size;
      grew = grew || (cap != i.oneLocation_value.capacity ());
    }

    // oneAmmoName_
    //
    {
      ::std::string const& v =
        o.oneAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.oneAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.oneAmmoName_value,
        size,
        is_null,
        v);
      i.oneAmmoName_null = is_null;
      i.oneAmmoName_size = size;
      grew = grew || (cap != i.oneAmmoName_value.capacity ());
    }

    // twoHangingPoint_
    //
    {
      ::std::string const& v =
        o.twoHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.twoHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.twoHangingPoint_value,
        size,
        is_null,
        v);
      i.twoHangingPoint_null = is_null;
      i.twoHangingPoint_size = size;
      grew = grew || (cap != i.twoHangingPoint_value.capacity ());
    }

    // twoLocation_
    //
    {
      ::std::string const& v =
        o.twoLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.twoLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.twoLocation_value,
        size,
        is_null,
        v);
      i.twoLocation_null = is_null;
      i.twoLocation_size = size;
      grew = grew || (cap != i.twoLocation_value.capacity ());
    }

    // twoAmmoName_
    //
    {
      ::std::string const& v =
        o.twoAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.twoAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.twoAmmoName_value,
        size,
        is_null,
        v);
      i.twoAmmoName_null = is_null;
      i.twoAmmoName_size = size;
      grew = grew || (cap != i.twoAmmoName_value.capacity ());
    }

    // threeHangingPoint_
    //
    {
      ::std::string const& v =
        o.threeHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.threeHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.threeHangingPoint_value,
        size,
        is_null,
        v);
      i.threeHangingPoint_null = is_null;
      i.threeHangingPoint_size = size;
      grew = grew || (cap != i.threeHangingPoint_value.capacity ());
    }

    // threeLocation_
    //
    {
      ::std::string const& v =
        o.threeLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.threeLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.threeLocation_value,
        size,
        is_null,
        v);
      i.threeLocation_null = is_null;
      i.threeLocation_size = size;
      grew = grew || (cap != i.threeLocation_value.capacity ());
    }

    // threeAmmoName_
    //
    {
      ::std::string const& v =
        o.threeAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.threeAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.threeAmmoName_value,
        size,
        is_null,
        v);
      i.threeAmmoName_null = is_null;
      i.threeAmmoName_size = size;
      grew = grew || (cap != i.threeAmmoName_value.capacity ());
    }

    // fourHangingPoint_
    //
    {
      ::std::string const& v =
        o.fourHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.fourHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.fourHangingPoint_value,
        size,
        is_null,
        v);
      i.fourHangingPoint_null = is_null;
      i.fourHangingPoint_size = size;
      grew = grew || (cap != i.fourHangingPoint_value.capacity ());
    }

    // fourLocation_
    //
    {
      ::std::string const& v =
        o.fourLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.fourLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.fourLocation_value,
        size,
        is_null,
        v);
      i.fourLocation_null = is_null;
      i.fourLocation_size = size;
      grew = grew || (cap != i.fourLocation_value.capacity ());
    }

    // fourAmmoName_
    //
    {
      ::std::string const& v =
        o.fourAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.fourAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.fourAmmoName_value,
        size,
        is_null,
        v);
      i.fourAmmoName_null = is_null;
      i.fourAmmoName_size = size;
      grew = grew || (cap != i.fourAmmoName_value.capacity ());
    }

    // fiveHangingPoint_
    //
    {
      ::std::string const& v =
        o.fiveHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.fiveHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.fiveHangingPoint_value,
        size,
        is_null,
        v);
      i.fiveHangingPoint_null = is_null;
      i.fiveHangingPoint_size = size;
      grew = grew || (cap != i.fiveHangingPoint_value.capacity ());
    }

    // fiveLocation_
    //
    {
      ::std::string const& v =
        o.fiveLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.fiveLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.fiveLocation_value,
        size,
        is_null,
        v);
      i.fiveLocation_null = is_null;
      i.fiveLocation_size = size;
      grew = grew || (cap != i.fiveLocation_value.capacity ());
    }

    // fiveAmmoName_
    //
    {
      ::std::string const& v =
        o.fiveAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.fiveAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.fiveAmmoName_value,
        size,
        is_null,
        v);
      i.fiveAmmoName_null = is_null;
      i.fiveAmmoName_size = size;
      grew = grew || (cap != i.fiveAmmoName_value.capacity ());
    }

    // sixHangingPoint_
    //
    {
      ::std::string const& v =
        o.sixHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.sixHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.sixHangingPoint_value,
        size,
        is_null,
        v);
      i.sixHangingPoint_null = is_null;
      i.sixHangingPoint_size = size;
      grew = grew || (cap != i.sixHangingPoint_value.capacity ());
    }

    // sixLocation_
    //
    {
      ::std::string const& v =
        o.sixLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.sixLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.sixLocation_value,
        size,
        is_null,
        v);
      i.sixLocation_null = is_null;
      i.sixLocation_size = size;
      grew = grew || (cap != i.sixLocation_value.capacity ());
    }

    // sixAmmoName_
    //
    {
      ::std::string const& v =
        o.sixAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.sixAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.sixAmmoName_value,
        size,
        is_null,
        v);
      i.sixAmmoName_null = is_null;
      i.sixAmmoName_size = size;
      grew = grew || (cap != i.sixAmmoName_value.capacity ());
    }

    // sevenHangingPoint_
    //
    {
      ::std::string const& v =
        o.sevenHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.sevenHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.sevenHangingPoint_value,
        size,
        is_null,
        v);
      i.sevenHangingPoint_null = is_null;
      i.sevenHangingPoint_size = size;
      grew = grew || (cap != i.sevenHangingPoint_value.capacity ());
    }

    // sevenLocation_
    //
    {
      ::std::string const& v =
        o.sevenLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.sevenLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.sevenLocation_value,
        size,
        is_null,
        v);
      i.sevenLocation_null = is_null;
      i.sevenLocation_size = size;
      grew = grew || (cap != i.sevenLocation_value.capacity ());
    }

    // sevenAmmoName_
    //
    {
      ::std::string const& v =
        o.sevenAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.sevenAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.sevenAmmoName_value,
        size,
        is_null,
        v);
      i.sevenAmmoName_null = is_null;
      i.sevenAmmoName_size = size;
      grew = grew || (cap != i.sevenAmmoName_value.capacity ());
    }

    // eightHangingPoint_
    //
    {
      ::std::string const& v =
        o.eightHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.eightHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.eightHangingPoint_value,
        size,
        is_null,
        v);
      i.eightHangingPoint_null = is_null;
      i.eightHangingPoint_size = size;
      grew = grew || (cap != i.eightHangingPoint_value.capacity ());
    }

    // eightLocation_
    //
    {
      ::std::string const& v =
        o.eightLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.eightLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.eightLocation_value,
        size,
        is_null,
        v);
      i.eightLocation_null = is_null;
      i.eightLocation_size = size;
      grew = grew || (cap != i.eightLocation_value.capacity ());
    }

    // eightAmmoName_
    //
    {
      ::std::string const& v =
        o.eightAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.eightAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.eightAmmoName_value,
        size,
        is_null,
        v);
      i.eightAmmoName_null = is_null;
      i.eightAmmoName_size = size;
      grew = grew || (cap != i.eightAmmoName_value.capacity ());
    }

    // nineHangingPoint_
    //
    {
      ::std::string const& v =
        o.nineHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.nineHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.nineHangingPoint_value,
        size,
        is_null,
        v);
      i.nineHangingPoint_null = is_null;
      i.nineHangingPoint_size = size;
      grew = grew || (cap != i.nineHangingPoint_value.capacity ());
    }

    // nineLocation_
    //
    {
      ::std::string const& v =
        o.nineLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.nineLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.nineLocation_value,
        size,
        is_null,
        v);
      i.nineLocation_null = is_null;
      i.nineLocation_size = size;
      grew = grew || (cap != i.nineLocation_value.capacity ());
    }

    // nineAmmoName_
    //
    {
      ::std::string const& v =
        o.nineAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.nineAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.nineAmmoName_value,
        size,
        is_null,
        v);
      i.nineAmmoName_null = is_null;
      i.nineAmmoName_size = size;
      grew = grew || (cap != i.nineAmmoName_value.capacity ());
    }

    // tenHangingPoint_
    //
    {
      ::std::string const& v =
        o.tenHangingPoint_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.tenHangingPoint_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.tenHangingPoint_value,
        size,
        is_null,
        v);
      i.tenHangingPoint_null = is_null;
      i.tenHangingPoint_size = size;
      grew = grew || (cap != i.tenHangingPoint_value.capacity ());
    }

    // tenLocation_
    //
    {
      ::std::string const& v =
        o.tenLocation_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.tenLocation_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.tenLocation_value,
        size,
        is_null,
        v);
      i.tenLocation_null = is_null;
      i.tenLocation_size = size;
      grew = grew || (cap != i.tenLocation_value.capacity ());
    }

    // tenAmmoName_
    //
    {
      ::std::string const& v =
        o.tenAmmoName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.tenAmmoName_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.tenAmmoName_value,
        size,
        is_null,
        v);
      i.tenAmmoName_null = is_null;
      i.tenAmmoName_size = size;
      grew = grew || (cap != i.tenAmmoName_value.capacity ());
    }

    // runningDistance_
    //
    {
      float const& v =
        o.runningDistance_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.runningDistance_value, is_null, v);
      i.runningDistance_null = is_null;
    }

    // endurance_
    //
    {
      float const& v =
        o.endurance_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.endurance_value, is_null, v);
      i.endurance_null = is_null;
    }

    // fightRadius_
    //
    {
      float const& v =
        o.fightRadius_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.fightRadius_value, is_null, v);
      i.fightRadius_null = is_null;
    }

    // maxFuel_
    //
    {
      float const& v =
        o.maxFuel_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.maxFuel_value, is_null, v);
      i.maxFuel_null = is_null;
    }

    // maxExternalWeight_
    //
    {
      float const& v =
        o.maxExternalWeight_;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.maxExternalWeight_value, is_null, v);
      i.maxExternalWeight_null = is_null;
    }

    // recordCreationTime_
    //
    {
      ::QDateTime const& v =
        o.recordCreationTime_;

      bool is_null (false);
      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_image (
        i.recordCreationTime_value, is_null, v);
      i.recordCreationTime_null = is_null;
    }

    // status_
    //
    {
      bool const& v =
        o.status_;

      bool is_null (false);
      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.status_value, is_null, v);
      i.status_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      long int& v =
        o.id_;

      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // mountSchemeName_
    //
    {
      ::std::string& v =
        o.mountSchemeName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.mountSchemeName_value,
        i.mountSchemeName_size,
        i.mountSchemeName_null);
    }

    // uavName_
    //
    {
      ::std::string& v =
        o.uavName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.uavName_value,
        i.uavName_size,
        i.uavName_null);
    }

    // maxTakeoffWeight_
    //
    {
      float& v =
        o.maxTakeoffWeight_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.maxTakeoffWeight_value,
        i.maxTakeoffWeight_null);
    }

    // emptyWeight_
    //
    {
      float& v =
        o.emptyWeight_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.emptyWeight_value,
        i.emptyWeight_null);
    }

    // oneHangingPoint_
    //
    {
      ::std::string& v =
        o.oneHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.oneHangingPoint_value,
        i.oneHangingPoint_size,
        i.oneHangingPoint_null);
    }

    // oneLocation_
    //
    {
      ::std::string& v =
        o.oneLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.oneLocation_value,
        i.oneLocation_size,
        i.oneLocation_null);
    }

    // oneAmmoName_
    //
    {
      ::std::string& v =
        o.oneAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.oneAmmoName_value,
        i.oneAmmoName_size,
        i.oneAmmoName_null);
    }

    // twoHangingPoint_
    //
    {
      ::std::string& v =
        o.twoHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.twoHangingPoint_value,
        i.twoHangingPoint_size,
        i.twoHangingPoint_null);
    }

    // twoLocation_
    //
    {
      ::std::string& v =
        o.twoLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.twoLocation_value,
        i.twoLocation_size,
        i.twoLocation_null);
    }

    // twoAmmoName_
    //
    {
      ::std::string& v =
        o.twoAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.twoAmmoName_value,
        i.twoAmmoName_size,
        i.twoAmmoName_null);
    }

    // threeHangingPoint_
    //
    {
      ::std::string& v =
        o.threeHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.threeHangingPoint_value,
        i.threeHangingPoint_size,
        i.threeHangingPoint_null);
    }

    // threeLocation_
    //
    {
      ::std::string& v =
        o.threeLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.threeLocation_value,
        i.threeLocation_size,
        i.threeLocation_null);
    }

    // threeAmmoName_
    //
    {
      ::std::string& v =
        o.threeAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.threeAmmoName_value,
        i.threeAmmoName_size,
        i.threeAmmoName_null);
    }

    // fourHangingPoint_
    //
    {
      ::std::string& v =
        o.fourHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.fourHangingPoint_value,
        i.fourHangingPoint_size,
        i.fourHangingPoint_null);
    }

    // fourLocation_
    //
    {
      ::std::string& v =
        o.fourLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.fourLocation_value,
        i.fourLocation_size,
        i.fourLocation_null);
    }

    // fourAmmoName_
    //
    {
      ::std::string& v =
        o.fourAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.fourAmmoName_value,
        i.fourAmmoName_size,
        i.fourAmmoName_null);
    }

    // fiveHangingPoint_
    //
    {
      ::std::string& v =
        o.fiveHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.fiveHangingPoint_value,
        i.fiveHangingPoint_size,
        i.fiveHangingPoint_null);
    }

    // fiveLocation_
    //
    {
      ::std::string& v =
        o.fiveLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.fiveLocation_value,
        i.fiveLocation_size,
        i.fiveLocation_null);
    }

    // fiveAmmoName_
    //
    {
      ::std::string& v =
        o.fiveAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.fiveAmmoName_value,
        i.fiveAmmoName_size,
        i.fiveAmmoName_null);
    }

    // sixHangingPoint_
    //
    {
      ::std::string& v =
        o.sixHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.sixHangingPoint_value,
        i.sixHangingPoint_size,
        i.sixHangingPoint_null);
    }

    // sixLocation_
    //
    {
      ::std::string& v =
        o.sixLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.sixLocation_value,
        i.sixLocation_size,
        i.sixLocation_null);
    }

    // sixAmmoName_
    //
    {
      ::std::string& v =
        o.sixAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.sixAmmoName_value,
        i.sixAmmoName_size,
        i.sixAmmoName_null);
    }

    // sevenHangingPoint_
    //
    {
      ::std::string& v =
        o.sevenHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.sevenHangingPoint_value,
        i.sevenHangingPoint_size,
        i.sevenHangingPoint_null);
    }

    // sevenLocation_
    //
    {
      ::std::string& v =
        o.sevenLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.sevenLocation_value,
        i.sevenLocation_size,
        i.sevenLocation_null);
    }

    // sevenAmmoName_
    //
    {
      ::std::string& v =
        o.sevenAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.sevenAmmoName_value,
        i.sevenAmmoName_size,
        i.sevenAmmoName_null);
    }

    // eightHangingPoint_
    //
    {
      ::std::string& v =
        o.eightHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.eightHangingPoint_value,
        i.eightHangingPoint_size,
        i.eightHangingPoint_null);
    }

    // eightLocation_
    //
    {
      ::std::string& v =
        o.eightLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.eightLocation_value,
        i.eightLocation_size,
        i.eightLocation_null);
    }

    // eightAmmoName_
    //
    {
      ::std::string& v =
        o.eightAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.eightAmmoName_value,
        i.eightAmmoName_size,
        i.eightAmmoName_null);
    }

    // nineHangingPoint_
    //
    {
      ::std::string& v =
        o.nineHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.nineHangingPoint_value,
        i.nineHangingPoint_size,
        i.nineHangingPoint_null);
    }

    // nineLocation_
    //
    {
      ::std::string& v =
        o.nineLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.nineLocation_value,
        i.nineLocation_size,
        i.nineLocation_null);
    }

    // nineAmmoName_
    //
    {
      ::std::string& v =
        o.nineAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.nineAmmoName_value,
        i.nineAmmoName_size,
        i.nineAmmoName_null);
    }

    // tenHangingPoint_
    //
    {
      ::std::string& v =
        o.tenHangingPoint_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.tenHangingPoint_value,
        i.tenHangingPoint_size,
        i.tenHangingPoint_null);
    }

    // tenLocation_
    //
    {
      ::std::string& v =
        o.tenLocation_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.tenLocation_value,
        i.tenLocation_size,
        i.tenLocation_null);
    }

    // tenAmmoName_
    //
    {
      ::std::string& v =
        o.tenAmmoName_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.tenAmmoName_value,
        i.tenAmmoName_size,
        i.tenAmmoName_null);
    }

    // runningDistance_
    //
    {
      float& v =
        o.runningDistance_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.runningDistance_value,
        i.runningDistance_null);
    }

    // endurance_
    //
    {
      float& v =
        o.endurance_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.endurance_value,
        i.endurance_null);
    }

    // fightRadius_
    //
    {
      float& v =
        o.fightRadius_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.fightRadius_value,
        i.fightRadius_null);
    }

    // maxFuel_
    //
    {
      float& v =
        o.maxFuel_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.maxFuel_value,
        i.maxFuel_null);
    }

    // maxExternalWeight_
    //
    {
      float& v =
        o.maxExternalWeight_;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.maxExternalWeight_value,
        i.maxExternalWeight_null);
    }

    // recordCreationTime_
    //
    {
      ::QDateTime& v =
        o.recordCreationTime_;

      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_value (
        v,
        i.recordCreationTime_value,
        i.recordCreationTime_null);
    }

    // status_
    //
    {
      bool& v =
        o.status_;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.status_value,
        i.status_null);
    }
  }

  void access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          long int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::persist_statement[] =
  "INSERT INTO \"uav_type_man\".\"uav_mount_scheme\" "
  "(\"id\", "
  "\"mount_scheme_name\", "
  "\"uav_name\", "
  "\"max_takeoff_weight\", "
  "\"empty_weight\", "
  "\"one_hanging_point\", "
  "\"one_location\", "
  "\"one_ammo_name\", "
  "\"two_hanging_point\", "
  "\"two_location\", "
  "\"two_ammo_name\", "
  "\"three_hanging_point\", "
  "\"three_location\", "
  "\"three_ammo_name\", "
  "\"four_hanging_point\", "
  "\"four_location\", "
  "\"four_ammo_name\", "
  "\"five_hanging_point\", "
  "\"five_location\", "
  "\"five_ammo_name\", "
  "\"six_hanging_point\", "
  "\"six_location\", "
  "\"six_ammo_name\", "
  "\"seven_hanging_point\", "
  "\"seven_location\", "
  "\"seven_ammo_name\", "
  "\"eight_hanging_point\", "
  "\"eight_location\", "
  "\"eight_ammo_name\", "
  "\"nine_hanging_point\", "
  "\"nine_location\", "
  "\"nine_ammo_name\", "
  "\"ten_hanging_point\", "
  "\"ten_location\", "
  "\"ten_ammo_name\", "
  "\"running_distance\", "
  "\"endurance\", "
  "\"fight_radius\", "
  "\"max_fuel\", "
  "\"max_external_weight\", "
  "\"recordcreation_time\", "
  "\"status\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::find_statement[] =
  "SELECT "
  "\"uav_type_man\".\"uav_mount_scheme\".\"id\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"mount_scheme_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"uav_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"max_takeoff_weight\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"empty_weight\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"one_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"one_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"one_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"two_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"two_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"two_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"three_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"three_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"three_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"four_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"four_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"four_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"five_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"five_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"five_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"six_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"six_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"six_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"seven_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"seven_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"seven_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"eight_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"eight_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"eight_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"nine_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"nine_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"nine_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"ten_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"ten_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"ten_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"running_distance\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"endurance\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"fight_radius\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"max_fuel\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"max_external_weight\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"recordcreation_time\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"status\" "
  "FROM \"uav_type_man\".\"uav_mount_scheme\" "
  "WHERE \"uav_type_man\".\"uav_mount_scheme\".\"id\"=$1";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::update_statement[] =
  "UPDATE \"uav_type_man\".\"uav_mount_scheme\" "
  "SET "
  "\"mount_scheme_name\"=$1, "
  "\"uav_name\"=$2, "
  "\"max_takeoff_weight\"=$3, "
  "\"empty_weight\"=$4, "
  "\"one_hanging_point\"=$5, "
  "\"one_location\"=$6, "
  "\"one_ammo_name\"=$7, "
  "\"two_hanging_point\"=$8, "
  "\"two_location\"=$9, "
  "\"two_ammo_name\"=$10, "
  "\"three_hanging_point\"=$11, "
  "\"three_location\"=$12, "
  "\"three_ammo_name\"=$13, "
  "\"four_hanging_point\"=$14, "
  "\"four_location\"=$15, "
  "\"four_ammo_name\"=$16, "
  "\"five_hanging_point\"=$17, "
  "\"five_location\"=$18, "
  "\"five_ammo_name\"=$19, "
  "\"six_hanging_point\"=$20, "
  "\"six_location\"=$21, "
  "\"six_ammo_name\"=$22, "
  "\"seven_hanging_point\"=$23, "
  "\"seven_location\"=$24, "
  "\"seven_ammo_name\"=$25, "
  "\"eight_hanging_point\"=$26, "
  "\"eight_location\"=$27, "
  "\"eight_ammo_name\"=$28, "
  "\"nine_hanging_point\"=$29, "
  "\"nine_location\"=$30, "
  "\"nine_ammo_name\"=$31, "
  "\"ten_hanging_point\"=$32, "
  "\"ten_location\"=$33, "
  "\"ten_ammo_name\"=$34, "
  "\"running_distance\"=$35, "
  "\"endurance\"=$36, "
  "\"fight_radius\"=$37, "
  "\"max_fuel\"=$38, "
  "\"max_external_weight\"=$39, "
  "\"recordcreation_time\"=$40, "
  "\"status\"=$41 "
  "WHERE \"id\"=$42";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::erase_statement[] =
  "DELETE FROM \"uav_type_man\".\"uav_mount_scheme\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::query_statement[] =
  "SELECT "
  "\"uav_type_man\".\"uav_mount_scheme\".\"id\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"mount_scheme_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"uav_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"max_takeoff_weight\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"empty_weight\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"one_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"one_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"one_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"two_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"two_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"two_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"three_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"three_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"three_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"four_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"four_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"four_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"five_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"five_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"five_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"six_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"six_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"six_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"seven_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"seven_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"seven_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"eight_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"eight_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"eight_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"nine_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"nine_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"nine_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"ten_hanging_point\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"ten_location\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"ten_ammo_name\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"running_distance\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"endurance\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"fight_radius\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"max_fuel\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"max_external_weight\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"recordcreation_time\", "
  "\"uav_type_man\".\"uav_mount_scheme\".\"status\" "
  "FROM \"uav_type_man\".\"uav_mount_scheme\"";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"uav_type_man\".\"uav_mount_scheme\"";

  const char access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::table_name[] =
  "\"uav_type_man\".\"uav_mount_scheme\"";

  void access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::pointer_type
  access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::object_type >
  access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
