// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef MOUNTING_SCHEME_ENTITY_ODB_HXX
#define MOUNTING_SCHEME_ENTITY_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "MountingSchemeEntity.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // UavMountSchemeEntity
  //
  template <>
  struct class_traits< ::UavMountSchemeEntity >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::UavMountSchemeEntity >
  {
    public:
    typedef ::UavMountSchemeEntity object_type;
    typedef ::UavMountSchemeEntity* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // UavMountSchemeEntity
  //
  template <typename A>
  struct query_columns< ::UavMountSchemeEntity, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // mountSchemeName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    mountSchemeName_type_;

    static const mountSchemeName_type_ mountSchemeName;

    // uavName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    uavName_type_;

    static const uavName_type_ uavName;

    // maxTakeoffWeight
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    maxTakeoffWeight_type_;

    static const maxTakeoffWeight_type_ maxTakeoffWeight;

    // emptyWeight
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    emptyWeight_type_;

    static const emptyWeight_type_ emptyWeight;

    // oneHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    oneHangingPoint_type_;

    static const oneHangingPoint_type_ oneHangingPoint;

    // oneLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    oneLocation_type_;

    static const oneLocation_type_ oneLocation;

    // oneAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    oneAmmoName_type_;

    static const oneAmmoName_type_ oneAmmoName;

    // twoHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    twoHangingPoint_type_;

    static const twoHangingPoint_type_ twoHangingPoint;

    // twoLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    twoLocation_type_;

    static const twoLocation_type_ twoLocation;

    // twoAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    twoAmmoName_type_;

    static const twoAmmoName_type_ twoAmmoName;

    // threeHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    threeHangingPoint_type_;

    static const threeHangingPoint_type_ threeHangingPoint;

    // threeLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    threeLocation_type_;

    static const threeLocation_type_ threeLocation;

    // threeAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    threeAmmoName_type_;

    static const threeAmmoName_type_ threeAmmoName;

    // fourHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    fourHangingPoint_type_;

    static const fourHangingPoint_type_ fourHangingPoint;

    // fourLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    fourLocation_type_;

    static const fourLocation_type_ fourLocation;

    // fourAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    fourAmmoName_type_;

    static const fourAmmoName_type_ fourAmmoName;

    // fiveHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    fiveHangingPoint_type_;

    static const fiveHangingPoint_type_ fiveHangingPoint;

    // fiveLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    fiveLocation_type_;

    static const fiveLocation_type_ fiveLocation;

    // fiveAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    fiveAmmoName_type_;

    static const fiveAmmoName_type_ fiveAmmoName;

    // sixHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    sixHangingPoint_type_;

    static const sixHangingPoint_type_ sixHangingPoint;

    // sixLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    sixLocation_type_;

    static const sixLocation_type_ sixLocation;

    // sixAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    sixAmmoName_type_;

    static const sixAmmoName_type_ sixAmmoName;

    // sevenHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    sevenHangingPoint_type_;

    static const sevenHangingPoint_type_ sevenHangingPoint;

    // sevenLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    sevenLocation_type_;

    static const sevenLocation_type_ sevenLocation;

    // sevenAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    sevenAmmoName_type_;

    static const sevenAmmoName_type_ sevenAmmoName;

    // eightHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    eightHangingPoint_type_;

    static const eightHangingPoint_type_ eightHangingPoint;

    // eightLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    eightLocation_type_;

    static const eightLocation_type_ eightLocation;

    // eightAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    eightAmmoName_type_;

    static const eightAmmoName_type_ eightAmmoName;

    // nineHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    nineHangingPoint_type_;

    static const nineHangingPoint_type_ nineHangingPoint;

    // nineLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    nineLocation_type_;

    static const nineLocation_type_ nineLocation;

    // nineAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    nineAmmoName_type_;

    static const nineAmmoName_type_ nineAmmoName;

    // tenHangingPoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    tenHangingPoint_type_;

    static const tenHangingPoint_type_ tenHangingPoint;

    // tenLocation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    tenLocation_type_;

    static const tenLocation_type_ tenLocation;

    // tenAmmoName
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    tenAmmoName_type_;

    static const tenAmmoName_type_ tenAmmoName;

    // runningDistance
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    runningDistance_type_;

    static const runningDistance_type_ runningDistance;

    // endurance
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    endurance_type_;

    static const endurance_type_ endurance;

    // fightRadius
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    fightRadius_type_;

    static const fightRadius_type_ fightRadius;

    // maxFuel
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    maxFuel_type_;

    static const maxFuel_type_ maxFuel;

    // maxExternalWeight
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        float,
        pgsql::id_real >::query_type,
      pgsql::id_real >
    maxExternalWeight_type_;

    static const maxExternalWeight_type_ maxExternalWeight;

    // recordCreationTime
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::QDateTime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    recordCreationTime_type_;

    static const recordCreationTime_type_ recordCreationTime;

    // status
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    status_type_;

    static const status_type_ status;
  };

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::id_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::mountSchemeName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  mountSchemeName (A::table_name, "\"mount_scheme_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::uavName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  uavName (A::table_name, "\"uav_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::maxTakeoffWeight_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  maxTakeoffWeight (A::table_name, "\"max_takeoff_weight\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::emptyWeight_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  emptyWeight (A::table_name, "\"empty_weight\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::oneHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  oneHangingPoint (A::table_name, "\"one_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::oneLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  oneLocation (A::table_name, "\"one_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::oneAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  oneAmmoName (A::table_name, "\"one_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::twoHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  twoHangingPoint (A::table_name, "\"two_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::twoLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  twoLocation (A::table_name, "\"two_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::twoAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  twoAmmoName (A::table_name, "\"two_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::threeHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  threeHangingPoint (A::table_name, "\"three_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::threeLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  threeLocation (A::table_name, "\"three_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::threeAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  threeAmmoName (A::table_name, "\"three_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::fourHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  fourHangingPoint (A::table_name, "\"four_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::fourLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  fourLocation (A::table_name, "\"four_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::fourAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  fourAmmoName (A::table_name, "\"four_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::fiveHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  fiveHangingPoint (A::table_name, "\"five_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::fiveLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  fiveLocation (A::table_name, "\"five_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::fiveAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  fiveAmmoName (A::table_name, "\"five_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::sixHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  sixHangingPoint (A::table_name, "\"six_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::sixLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  sixLocation (A::table_name, "\"six_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::sixAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  sixAmmoName (A::table_name, "\"six_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::sevenHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  sevenHangingPoint (A::table_name, "\"seven_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::sevenLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  sevenLocation (A::table_name, "\"seven_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::sevenAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  sevenAmmoName (A::table_name, "\"seven_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::eightHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  eightHangingPoint (A::table_name, "\"eight_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::eightLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  eightLocation (A::table_name, "\"eight_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::eightAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  eightAmmoName (A::table_name, "\"eight_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::nineHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  nineHangingPoint (A::table_name, "\"nine_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::nineLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  nineLocation (A::table_name, "\"nine_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::nineAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  nineAmmoName (A::table_name, "\"nine_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::tenHangingPoint_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  tenHangingPoint (A::table_name, "\"ten_hanging_point\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::tenLocation_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  tenLocation (A::table_name, "\"ten_location\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::tenAmmoName_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  tenAmmoName (A::table_name, "\"ten_ammo_name\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::runningDistance_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  runningDistance (A::table_name, "\"running_distance\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::endurance_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  endurance (A::table_name, "\"endurance\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::fightRadius_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  fightRadius (A::table_name, "\"fight_radius\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::maxFuel_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  maxFuel (A::table_name, "\"max_fuel\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::maxExternalWeight_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  maxExternalWeight (A::table_name, "\"max_external_weight\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::recordCreationTime_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  recordCreationTime (A::table_name, "\"recordcreation_time\"", 0);

  template <typename A>
  const typename query_columns< ::UavMountSchemeEntity, id_pgsql, A >::status_type_
  query_columns< ::UavMountSchemeEntity, id_pgsql, A >::
  status (A::table_name, "\"status\"", 0);

  template <typename A>
  struct pointer_query_columns< ::UavMountSchemeEntity, id_pgsql, A >:
    query_columns< ::UavMountSchemeEntity, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >:
    public access::object_traits< ::UavMountSchemeEntity >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // mountSchemeName_
      //
      details::buffer mountSchemeName_value;
      std::size_t mountSchemeName_size;
      bool mountSchemeName_null;

      // uavName_
      //
      details::buffer uavName_value;
      std::size_t uavName_size;
      bool uavName_null;

      // maxTakeoffWeight_
      //
      float maxTakeoffWeight_value;
      bool maxTakeoffWeight_null;

      // emptyWeight_
      //
      float emptyWeight_value;
      bool emptyWeight_null;

      // oneHangingPoint_
      //
      details::buffer oneHangingPoint_value;
      std::size_t oneHangingPoint_size;
      bool oneHangingPoint_null;

      // oneLocation_
      //
      details::buffer oneLocation_value;
      std::size_t oneLocation_size;
      bool oneLocation_null;

      // oneAmmoName_
      //
      details::buffer oneAmmoName_value;
      std::size_t oneAmmoName_size;
      bool oneAmmoName_null;

      // twoHangingPoint_
      //
      details::buffer twoHangingPoint_value;
      std::size_t twoHangingPoint_size;
      bool twoHangingPoint_null;

      // twoLocation_
      //
      details::buffer twoLocation_value;
      std::size_t twoLocation_size;
      bool twoLocation_null;

      // twoAmmoName_
      //
      details::buffer twoAmmoName_value;
      std::size_t twoAmmoName_size;
      bool twoAmmoName_null;

      // threeHangingPoint_
      //
      details::buffer threeHangingPoint_value;
      std::size_t threeHangingPoint_size;
      bool threeHangingPoint_null;

      // threeLocation_
      //
      details::buffer threeLocation_value;
      std::size_t threeLocation_size;
      bool threeLocation_null;

      // threeAmmoName_
      //
      details::buffer threeAmmoName_value;
      std::size_t threeAmmoName_size;
      bool threeAmmoName_null;

      // fourHangingPoint_
      //
      details::buffer fourHangingPoint_value;
      std::size_t fourHangingPoint_size;
      bool fourHangingPoint_null;

      // fourLocation_
      //
      details::buffer fourLocation_value;
      std::size_t fourLocation_size;
      bool fourLocation_null;

      // fourAmmoName_
      //
      details::buffer fourAmmoName_value;
      std::size_t fourAmmoName_size;
      bool fourAmmoName_null;

      // fiveHangingPoint_
      //
      details::buffer fiveHangingPoint_value;
      std::size_t fiveHangingPoint_size;
      bool fiveHangingPoint_null;

      // fiveLocation_
      //
      details::buffer fiveLocation_value;
      std::size_t fiveLocation_size;
      bool fiveLocation_null;

      // fiveAmmoName_
      //
      details::buffer fiveAmmoName_value;
      std::size_t fiveAmmoName_size;
      bool fiveAmmoName_null;

      // sixHangingPoint_
      //
      details::buffer sixHangingPoint_value;
      std::size_t sixHangingPoint_size;
      bool sixHangingPoint_null;

      // sixLocation_
      //
      details::buffer sixLocation_value;
      std::size_t sixLocation_size;
      bool sixLocation_null;

      // sixAmmoName_
      //
      details::buffer sixAmmoName_value;
      std::size_t sixAmmoName_size;
      bool sixAmmoName_null;

      // sevenHangingPoint_
      //
      details::buffer sevenHangingPoint_value;
      std::size_t sevenHangingPoint_size;
      bool sevenHangingPoint_null;

      // sevenLocation_
      //
      details::buffer sevenLocation_value;
      std::size_t sevenLocation_size;
      bool sevenLocation_null;

      // sevenAmmoName_
      //
      details::buffer sevenAmmoName_value;
      std::size_t sevenAmmoName_size;
      bool sevenAmmoName_null;

      // eightHangingPoint_
      //
      details::buffer eightHangingPoint_value;
      std::size_t eightHangingPoint_size;
      bool eightHangingPoint_null;

      // eightLocation_
      //
      details::buffer eightLocation_value;
      std::size_t eightLocation_size;
      bool eightLocation_null;

      // eightAmmoName_
      //
      details::buffer eightAmmoName_value;
      std::size_t eightAmmoName_size;
      bool eightAmmoName_null;

      // nineHangingPoint_
      //
      details::buffer nineHangingPoint_value;
      std::size_t nineHangingPoint_size;
      bool nineHangingPoint_null;

      // nineLocation_
      //
      details::buffer nineLocation_value;
      std::size_t nineLocation_size;
      bool nineLocation_null;

      // nineAmmoName_
      //
      details::buffer nineAmmoName_value;
      std::size_t nineAmmoName_size;
      bool nineAmmoName_null;

      // tenHangingPoint_
      //
      details::buffer tenHangingPoint_value;
      std::size_t tenHangingPoint_size;
      bool tenHangingPoint_null;

      // tenLocation_
      //
      details::buffer tenLocation_value;
      std::size_t tenLocation_size;
      bool tenLocation_null;

      // tenAmmoName_
      //
      details::buffer tenAmmoName_value;
      std::size_t tenAmmoName_size;
      bool tenAmmoName_null;

      // runningDistance_
      //
      float runningDistance_value;
      bool runningDistance_null;

      // endurance_
      //
      float endurance_value;
      bool endurance_null;

      // fightRadius_
      //
      float fightRadius_value;
      bool fightRadius_null;

      // maxFuel_
      //
      float maxFuel_value;
      bool maxFuel_null;

      // maxExternalWeight_
      //
      float maxExternalWeight_value;
      bool maxExternalWeight_null;

      // recordCreationTime_
      //
      unsigned long long recordCreationTime_value;
      bool recordCreationTime_null;

      // status_
      //
      bool status_value;
      bool status_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 42UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::UavMountSchemeEntity, id_common >:
    public access::object_traits_impl< ::UavMountSchemeEntity, id_pgsql >
  {
  };

  // UavMountSchemeEntity
  //
}

#include "MountingSchemeEntity-odb.ixx"

#include <odb/post.hxx>

#endif // MOUNTING_SCHEME_ENTITY_ODB_HXX
