/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "uav_type_man"."reconnaissance_payload" CASCADE;

CREATE TABLE "uav_type_man"."reconnaissance_payload" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "reconnaissancepayload_name" TEXT NOT NULL,
  "reconnaissancepayload_id" TEXT NOT NULL,
  "length" REAL NOT NULL,
  "width" REAL NOT NULL,
  "height" REAL NOT NULL,
  "reconnaissance_accuracy" TEXT NOT NULL,
  "data_returndeadline" REAL NOT NULL,
  "working_height_minimum" REAL NOT NULL,
  "working_height_maximum" REAL NOT NULL,
  "working_speed_minimum" REAL NOT NULL,
  "working_speed_maximum" REAL NOT NULL,
  "working_pitch_minimum" REAL NOT NULL,
  "working_pitch_maximum" REAL NOT NULL,
  "image_name" REAL NOT NULL,
  "loadimage_path" REAL NOT NULL,
  "recordcreation_time" TEXT NOT NULL);

