/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "uav_type_man"."uav_model_type" CASCADE;

CREATE TABLE "uav_type_man"."uav_model_type" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "uavmodel_type_code" TEXT NOT NULL,
  "uavmodel_type_name" TEXT NOT NULL,
  "status" BOOLEAN NOT NULL);

