/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "public"."uav_model_mount_location" CASCADE;

CREATE TABLE "public"."uav_model_mount_location" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "mount_location_id" TEXT NOT NULL,
  "mountlocation_name" TEXT NOT NULL);

